create or replace function FN_IRB_EXEMP_FORM_ACTION_LOG(
AV_IRB_PERSON_EXEMPT_FORM_ID		IRB_EXEMPT_FORM_ACTN_LOG.IRB_PERSON_EXEMPT_FORM_ID%TYPE,
AV_ACTION_TYPE_CODE					IRB_EXEMPT_FORM_ACTN_LOG.ACTION_TYPE_CODE%TYPE,
AV_COMMENT							IRB_EXEMPT_FORM_ACTN_LOG.COMMENTS%TYPE,
AV_EXEMPT_STATUS_CODE				IRB_EXEMPT_FORM_ACTN_LOG.EXEMPT_STATUS_CODE%TYPE,
AV_UPDATE_USER						IRB_EXEMPT_FORM_ACTN_LOG.UPDATE_USER%TYPE
)RETURN NUMBER
IS
BEGIN
	INSERT INTO IRB_EXEMPT_FORM_ACTN_LOG(
		EXEMPT_FORM_ACTN_LOG_ID,
		IRB_PERSON_EXEMPT_FORM_ID,
		ACTION_TYPE_CODE,
		COMMENTS,
		EXEMPT_STATUS_CODE,
		UPDATE_TIMESTAMP,
		UPDATE_USER
	)
	VALUES(
		SEQ_EXEMPT_FORM_ACTN_LOG_ID.NEXTVAL,
		AV_IRB_PERSON_EXEMPT_FORM_ID,
		AV_ACTION_TYPE_CODE,
		AV_COMMENT,
		AV_EXEMPT_STATUS_CODE,
		SYSDATE,
		AV_UPDATE_USER		
	);

	RETURN 1;	

END;
/
