create or replace procedure GET_IRB_PROTOCOL_VULNBLE_SUBJT(
AV_PROTOCOL_NUMBER  IN IRB_PROTOCOL.protocol_number%type,
CUR_GENERIC         OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN CUR_GENERIC FOR
		SELECT 			
			t3.description as VULNERABLE_SUBJECT,
			t2.SUBJECT_COUNT
		FROM IRB_PROTOCOL t1
		INNER JOIN IRB_PROTO_VULNERABLE_SUB t2 on t1.PROTOCOL_ID = t2.PROTOCOL_ID
		INNER JOIN IRB_VULNERABLE_SUBJECT_TYPE	t3 on t2.VULNERABLE_SUBJECT_TYPE_CODE = t3.VULNERABLE_SUBJECT_TYPE_CODE
		WHERE t1.is_latest = 'Y'
		AND t1.protocol_number = AV_PROTOCOL_NUMBER
		ORDER BY t2.PROTOCOL_VULNERABLE_SUB_ID;
END;
/