create or replace PROCEDURE GET_IRB_PROTOCOL_TYPE(
CUR_GENERIC         OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN CUR_GENERIC FOR
  SELECT PROTOCOL_TYPE_CODE,
         DESCRIPTION as PROTOCOL_TYPE
  FROM MITKC_IRB_PROTOCOL_TYPE;       
END;
/