create or replace PROCEDURE GET_IRB_EXEMPT_FORM_ACTION_LOG(
AV_IRB_PERSON_EXEMPT_FORM_ID IN  MITKC_IRB_EXEMPT_FORM_ACTN_LOG.IRB_PERSON_EXEMPT_FORM_ID%TYPE,
CUR_GENERIC OUT SYS_REFCURSOR)
IS
BEGIN
	OPEN CUR_GENERIC FOR
	SELECT 
		t1.EXEMPT_FORM_ACTN_LOG_ID,
		t1.IRB_PERSON_EXEMPT_FORM_ID,
		t1.ACTION_TYPE_CODE,
		t3.DESCRIPTION as ACTION_TYPE,
		T4.DESCRIPTION as EXEMPT_STATUS,
		t1.COMMENTS,
		t1.EXEMPT_STATUS_CODE,
		to_char(t1.UPDATE_TIMESTAMP,'YYYY-MM-DD hh:mi:ss AM') as UPDATE_TIMESTAMP,
		nvl(t2.full_name,t1.UPDATE_USER) as UPDATE_USER	
	FROM MITKC_IRB_EXEMPT_FORM_ACTN_LOG t1
	LEFT OUTER JOIN KC_PERSON_MV t2 on (t2.PRNCPL_NM) = (t1.update_user)
	INNER JOIN MITKC_IRB_EXEMPT_ACTION_TYPE t3 on t3.ACTION_TYPE_CODE = t1.ACTION_TYPE_CODE
	INNER JOIN MITKC_IRB_EXEMPT_FORM_STATUS t4 on t4.EXEMPT_STATUS_CODE = t1.EXEMPT_STATUS_CODE
	WHERE t1.IRB_PERSON_EXEMPT_FORM_ID = AV_IRB_PERSON_EXEMPT_FORM_ID
	ORDER BY t1.EXEMPT_FORM_ACTN_LOG_ID desc;
END;
/