create or replace PROCEDURE GET_IRB_EXEMPT_FORM_CHECKLST(
AV_IRB_PERSON_EXEMPT_FORM_ID IN  MITKC_IRB_EXEMPT_FORM_CHECKLST.IRB_PERSON_EXEMPT_FORM_ID%TYPE,
CUR_GENERIC OUT SYS_REFCURSOR)
IS
BEGIN
	OPEN CUR_GENERIC FOR
	SELECT 
		t1.EXEMPT_FORM_CHECKLST_ID,
		t1.IRB_PERSON_EXEMPT_FORM_ID,
		t1.DESCRIPTION,
		t1.FILENAME,	
		t1.CONTENT_TYPE,
		to_char(t1.UPDATE_TIMESTAMP,'YYYY-MM-DD') as UPDATE_TIMESTAMP,
		nvl(t2.full_name,t1.UPDATE_USER) as UPDATE_USER		
	FROM MITKC_IRB_EXEMPT_FORM_CHECKLST t1
	LEFT OUTER JOIN KC_PERSON_MV t2 on (t2.PRNCPL_NM) = (t1.update_user)
	WHERE t1.IRB_PERSON_EXEMPT_FORM_ID = AV_IRB_PERSON_EXEMPT_FORM_ID;
END;
/