create or replace procedure GET_MITKC_PERSON_TRAINING_INFO(
AV_PERSON_ID  		IN VARCHAR2,
CUR_GENERIC         OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN CUR_GENERIC FOR
		SELECT 					
			PERSON_ID,			
			TRAINING_DESCRIPTION,
			DATE_SUBMITTED,
			FOLLOWUP_DATE,
			SCORE
		FROM WHOSP_PERSON_TRAINING
		WHERE PERSON_ID = AV_PERSON_ID
		ORDER BY TRAINING_NUMBER;
END;
/