create or replace procedure GET_MITKC_PERSON_INFO(
AV_PERSON_ID  		IN VARCHAR2,
CUR_GENERIC         OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN CUR_GENERIC FOR
		SELECT 					
			PERSON_ID,
			FULL_NAME,
			USER_NAME,
			EMAIL_ADDRESS,
			PRIMARY_TITLE,
			DIRECTORY_TITLE,
			HOME_UNIT,
			ADDRESS_LINE_1,
			CITY,
			STATE,
			POSTAL_CODE,
			COUNTRY_CODE,
			MOBILE_PHONE_NUMBER,
			OFFICE_PHONE,
			OFFICE_LOCATION
		FROM OSP$PERSON
		WHERE PERSON_ID = AV_PERSON_ID;
END;
/