create or replace procedure GET_IRB_PROTOCOL_FUNDING_SRC(
AV_PROTOCOL_NUMBER  IN IRB_PROTOCOL.protocol_number%type,
CUR_GENERIC         OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN CUR_GENERIC FOR
		SELECT 
			t3.FUNDING_SOURCE_TYPE_FLAG,
			t2.FUNDING_SOURCE,
			t4.ACCOUNT_NUMBER,
			t2.FUNDING_SOURCE_NAME,
			t3.description as FUNDING_SOURCE_TYPE
		FROM IRB_PROTOCOL t1
		INNER JOIN IRB_PROTO_FUNDING_SOURCE t2 on t1.PROTOCOL_ID = t2.PROTOCOL_ID
		INNER JOIN FUNDING_SOURCE_TYPE	t3 on t2.FUNDING_SOURCE_TYPE_CODE = t3.FUNDING_SOURCE_TYPE_CODE
		LEFT OUTER JOIN AWARD t4 on t4.AWARD_NUMBER = t2.FUNDING_SOURCE and t4.AWARD_SEQUENCE_STATUS = 'ACTIVE'
		WHERE t1.is_latest = 'Y'
		AND t1.protocol_number = AV_PROTOCOL_NUMBER;
END;
/