create or replace procedure GET_IRB_PROTOCOL_LOCATION(
AV_PROTOCOL_NUMBER  IN IRB_PROTOCOL.protocol_number%type,
CUR_GENERIC         OUT SYS_REFCURSOR
)IS
BEGIN
    OPEN CUR_GENERIC FOR
		SELECT 
		(t3.LAST_NAME||', '||t3.FIRST_NAME||' '|| t3.MIDDLE_NAME) as ROLODEX_NAME,
		t3.EMAIL_ADDRESS as ROLODEX_EMAIL_ADDRESS,
		t3.PHONE_NUMBER as ROLODEX_PHONE_NUMBER,
		t4.ORGANIZATION_NAME,
		'' as EXPIRATION_DATE,
		'' as APPROVAL_DATE
		FROM IRB_PROTOCOL t1
		INNER JOIN IRB_PROTOCOL_LOCATION t2 on t1.PROTOCOL_ID = t2.PROTOCOL_ID
		LEFT OUTER JOIN ROLODEX t3 on t2.ROLODEX_ID = t3.ROLODEX_ID
		LEFT OUTER JOIN ORGANIZATION t4 on t2.ORGANIZATION_ID = t4.ORGANIZATION_ID   
		WHERE t1.is_latest = 'Y'
		AND t1.protocol_number = AV_PROTOCOL_NUMBER
		ORDER by t2.PROTOCOL_LOCATION_ID;
END;
/