create or replace PROCEDURE GET_IRB_NOT_EXEMPT_QSTN_LIST(
AV_IRB_PERSON_EXEMPT_FORM_ID IN  MITKC_IRB_PERSON_EXEMPT_FORM.IRB_PERSON_EXEMPT_FORM_ID%TYPE,
CUR_GENERIC OUT SYS_REFCURSOR)
IS
li_qnr_ans_hdr 	MITKC_IRB_PERSON_EXEMPT_FORM.QUESTIONNAIRE_ANS_HEADER_ID%TYPE;  
li_count 			NUMBER;
ls_question     MITKC_QUESTIONNAIRE_QUESTION.QUESTION%TYPE;
ls_question_id  MITKC_QUESTIONNAIRE_QUESTION.QUESTION_ID%TYPE;
BEGIN

	BEGIN
		SELECT QUESTIONNAIRE_ANS_HEADER_ID
		INTO li_qnr_ans_hdr
		FROM MITKC_IRB_PERSON_EXEMPT_FORM
		WHERE IRB_PERSON_EXEMPT_FORM_ID = AV_IRB_PERSON_EXEMPT_FORM_ID;
	EXCEPTION
	WHEN OTHERS THEN 
		li_qnr_ans_hdr := -1;
	END;

	OPEN CUR_GENERIC FOR
	
		SELECT 0 as QUESTION_ID
		FROM MITKC_QUESTIONNAIRE_ANSWER
		WHERE QUESTIONNAIRE_ANS_HEADER_ID = li_qnr_ans_hdr
		AND QUESTION_ID IN (170,169)
		AND ANSWER = 'No'
		
		UNION
		
		SELECT QUESTION_ID
		FROM MITKC_QUESTIONNAIRE_ANSWER
		WHERE QUESTIONNAIRE_ANS_HEADER_ID = li_qnr_ans_hdr
		AND QUESTION_ID IN (172,176,180,187,193)
		AND ANSWER = 'No'
		
		UNION
		
		SELECT QUESTION_ID
		FROM MITKC_QUESTIONNAIRE_ANSWER
		WHERE QUESTIONNAIRE_ANS_HEADER_ID = li_qnr_ans_hdr
		AND QUESTION_ID IN (174,179,182,186,189,196)
		AND ANSWER = 'Yes'
		
		UNION
		
    -- Wrong determination when all exempt categories = N
		SELECT QUESTION_ID FROM MITKC_QUESTIONNAIRE_ANSWER T1
		WHERE T1.QUESTIONNAIRE_ANS_HEADER_ID = LI_QNR_ANS_HDR 
		AND T1.QUESTION_ID IN (173,183,175,190,194)
		AND 5 = (
				 SELECT COUNT(T2.QUESTION_ID) FROM MITKC_QUESTIONNAIRE_ANSWER T2 
				 WHERE T2.QUESTIONNAIRE_ANS_HEADER_ID = LI_QNR_ANS_HDR
				 AND  T2.QUESTION_ID IN (173,183,175,190,194)
				 AND T2.ANSWER = 'No' 
				 );
	
	
		
END;
/