create or replace PROCEDURE GET_IRB_EXEMPT_FORM_CKLST_FILE(
AV_EXEMPT_FORM_CHECKLST_ID IN  MITKC_IRB_EXEMPT_FORM_CHECKLST.EXEMPT_FORM_CHECKLST_ID%TYPE,
CUR_GENERIC OUT SYS_REFCURSOR)
IS
BEGIN
	OPEN CUR_GENERIC FOR
	SELECT 
		t1.FILE_DATA,
		t1.FILENAME,	
		t1.CONTENT_TYPE			
	FROM MITKC_IRB_EXEMPT_FORM_CHECKLST t1
	WHERE t1.EXEMPT_FORM_CHECKLST_ID = AV_EXEMPT_FORM_CHECKLST_ID;
END;
/