create or replace PROCEDURE UPD_IRB_PERSON_EXEMPT_FORM(
AV_IRB_PERSON_EXEMPT_FORM_ID	IN MITKC_IRB_PERSON_EXEMPT_FORM.IRB_PERSON_EXEMPT_FORM_ID%TYPE,
AV_PERSON_ID					IN MITKC_IRB_PERSON_EXEMPT_FORM.PERSON_ID%TYPE,
AV_PERSON_NAME					IN MITKC_IRB_PERSON_EXEMPT_FORM.PERSON_NAME%TYPE,
AV_EXEMPT_FORM_NUMBER			IN MITKC_IRB_PERSON_EXEMPT_FORM.EXEMPT_FORM_NUMBER%TYPE,
AV_EXEMPT_STATUS_CODE			IN MITKC_IRB_PERSON_EXEMPT_FORM.EXEMPT_STATUS_CODE%TYPE,
AV_IS_EXEMPT_GRANTED			IN MITKC_IRB_PERSON_EXEMPT_FORM.IS_EXEMPT_GRANTED%TYPE,
AV_EXEMPT_TITLE					IN MITKC_IRB_PERSON_EXEMPT_FORM.EXEMPT_TITLE%TYPE,
AV_QUESTIONNAIRE_ANS_HEADER_ID  IN MITKC_IRB_PERSON_EXEMPT_FORM.QUESTIONNAIRE_ANS_HEADER_ID%TYPE,
AV_FACULTY_SPONSOR_PERSON_ID    IN MITKC_IRB_PERSON_EXEMPT_FORM.FACULTY_SPONSOR_PERSON_ID%TYPE,
AV_UNIT_NUMBER    				IN MITKC_IRB_PERSON_EXEMPT_FORM.UNIT_NUMBER%TYPE,
AV_UPDATE_USER					IN MITKC_IRB_PERSON_EXEMPT_FORM.UPDATE_USER%TYPE,
AV_SUMMARY						IN MITKC_IRB_PERSON_EXEMPT_FORM.SUMMARY%TYPE,
AV_START_DATE					IN MITKC_IRB_PERSON_EXEMPT_FORM.START_DATE%TYPE,
AV_END_DATE						IN MITKC_IRB_PERSON_EXEMPT_FORM.END_DATE%TYPE,
AC_TYPE						IN VARCHAR2
)
IS
li_exempt_form_number MITKC_IRB_PERSON_EXEMPT_FORM.EXEMPT_FORM_NUMBER%TYPE;

BEGIN
	
	IF 	AC_TYPE = 'I' THEN
		
		SELECT max(EXEMPT_FORM_NUMBER)
		INTO li_exempt_form_number
		FROM MITKC_IRB_PERSON_EXEMPT_FORM
		WHERE PERSON_ID = AV_PERSON_ID;
		
		IF li_exempt_form_number is null THEN
			li_exempt_form_number := 0;
		END IF;
	
		li_exempt_form_number := li_exempt_form_number + 1;
		
		INSERT INTO MITKC_IRB_PERSON_EXEMPT_FORM(
			IRB_PERSON_EXEMPT_FORM_ID,
			PERSON_ID,
			PERSON_NAME,
			EXEMPT_FORM_NUMBER,
			EXEMPT_STATUS_CODE,
			IS_EXEMPT_GRANTED,
			EXEMPT_TITLE,
			QUESTIONNAIRE_ANS_HEADER_ID,
			FACULTY_SPONSOR_PERSON_ID,
			UNIT_NUMBER,
			CREATE_USER,
			CREATE_TIMESTAMP,
			UPDATE_TIMESTAMP,
			SUMMARY,
			START_DATE,
			END_DATE,
			UPDATE_USER
		)
		VALUES(
			AV_IRB_PERSON_EXEMPT_FORM_ID,
			AV_PERSON_ID,
			AV_PERSON_NAME,
			li_exempt_form_number,
			AV_EXEMPT_STATUS_CODE,
			AV_IS_EXEMPT_GRANTED,
			AV_EXEMPT_TITLE,
			AV_QUESTIONNAIRE_ANS_HEADER_ID,
			AV_FACULTY_SPONSOR_PERSON_ID,
			AV_UNIT_NUMBER,
			AV_UPDATE_USER,
			SYSDATE,
			SYSDATE,
			AV_SUMMARY,
			AV_START_DATE,
			AV_END_DATE	,
			AV_UPDATE_USER
		);
	ELSIF  AC_TYPE = 'U' THEN
		UPDATE MITKC_IRB_PERSON_EXEMPT_FORM
		SET  QUESTIONNAIRE_ANS_HEADER_ID = AV_QUESTIONNAIRE_ANS_HEADER_ID,
					  EXEMPT_STATUS_CODE = AV_EXEMPT_STATUS_CODE,
					   IS_EXEMPT_GRANTED = AV_IS_EXEMPT_GRANTED,
					   FACULTY_SPONSOR_PERSON_ID = AV_FACULTY_SPONSOR_PERSON_ID,
					   UNIT_NUMBER = AV_UNIT_NUMBER,
					   SUMMARY = AV_SUMMARY,
					   START_DATE = AV_START_DATE,
					   END_DATE = AV_END_DATE,
					   EXEMPT_TITLE = NVL(AV_EXEMPT_TITLE,EXEMPT_TITLE)
		WHERE IRB_PERSON_EXEMPT_FORM_ID = AV_IRB_PERSON_EXEMPT_FORM_ID;
	
	ELSIF  AC_TYPE = 'D' THEN
		DELETE FROM MITKC_IRB_PERSON_EXEMPT_FORM WHERE IRB_PERSON_EXEMPT_FORM_ID = AV_IRB_PERSON_EXEMPT_FORM_ID;
	
	END IF;
END;
/