CREATE TABLE "MITKC_IRB_PROTOCOL_TYPE"(
"PROTOCOL_TYPE_CODE" VARCHAR2(3 BYTE), 
"DESCRIPTION" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
CONSTRAINT "MITKC_IRB_PROTOCOL_TYPE_PK" PRIMARY KEY ("PROTOCOL_TYPE_CODE")
)
/
CREATE TABLE "MITKC_IRB_PROTO_CORRESP_TYPE" 
(	"PROTO_CORRESP_TYPE_CODE" VARCHAR2(3 BYTE), 
"DESCRIPTION" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
"MODULE_ID" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE, 
"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
CONSTRAINT "MITKC_IRB_CORRESP_TYPE_PK" PRIMARY KEY ("PROTO_CORRESP_TYPE_CODE")
)
/
CREATE TABLE "MITKC_IRB_PROTOCOL_REVIEW_TYPE" 
(	
"PROTOCOL_REVIEW_TYPE_CODE" VARCHAR2(3 BYTE), 
"DESCRIPTION" VARCHAR2(200 BYTE) NOT NULL, 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL,
"GLOBAL_FLAG" VARCHAR2(1 BYTE) DEFAULT 'Y',
CONSTRAINT "MITKC_IRB_PROTO_REVIEW_TYPE_PK" PRIMARY KEY ("PROTOCOL_REVIEW_TYPE_CODE")
)
/
CREATE TABLE "MITKC_IRB_PROTO_ATT_GROUP" 
(	
"GROUP_CD" 		VARCHAR2(3 BYTE), 
"DESCRIPTION" 	VARCHAR2(300 BYTE) NOT NULL, 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL,
CONSTRAINT "MITKC_IRB_PROTO_ATT_GROUP_PK" PRIMARY KEY ("GROUP_CD")	
) 
/
CREATE TABLE "MITKC_IRB_PROTO_REFERENCE_TYPE" 
(	
"PROTOCOL_REFERENCE_TYPE_CODE" NUMBER(3,0), 
"DESCRIPTION" VARCHAR2(200 BYTE) NOT NULL, 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL,  
"ACTIVE_FLAG" VARCHAR2(1 BYTE),
CONSTRAINT "MITKC_IRB_REFERENCE_TYPE_PK" PRIMARY KEY ("PROTOCOL_REFERENCE_TYPE_CODE")	
)
/
CREATE TABLE "MITKC_IRB_PERSON_ROLES"(
"PROTOCOL_PERSON_ROLE_ID" VARCHAR2(12 BYTE), 
"DESCRIPTION" VARCHAR2(250 BYTE) NOT NULL , 
"UNIT_DETAILS_REQUIRED" VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL , 
"UPDATE_TIMESTAMP" 				DATE, 
"UPDATE_USER" 				VARCHAR2(60 BYTE), 
"AFFILIATION_DETAILS_REQUIRED" VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL , 
"TRAINING_DETAILS_REQUIRED" 	VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL , 
"COMMENTS_DETAILS_REQUIRED"		 VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL , 
"ACTIVE_FLAG" 					VARCHAR2(1 BYTE) NOT NULL 
)
/
CREATE UNIQUE INDEX "MITKC_IRB_PERSON_ROLES_PK" ON "MITKC_IRB_PERSON_ROLES" ("PROTOCOL_PERSON_ROLE_ID") 
/
ALTER TABLE "MITKC_IRB_PERSON_ROLES" ADD CONSTRAINT "MITKC_IRB_PERSON_ROLES_PK" PRIMARY KEY ("PROTOCOL_PERSON_ROLE_ID")
/
CREATE TABLE "MITKC_IRB_ATTACHMENT_STATUS" 
(	
"STATUS_CD" VARCHAR2(3 BYTE), 
"DESCRIPTION" VARCHAR2(300 BYTE) NOT NULL,
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL
)
/
CREATE UNIQUE INDEX "MITKC_IRB_ATTACHMENT_STATUS_PK" ON "MITKC_IRB_ATTACHMENT_STATUS" ("STATUS_CD") 
/
ALTER TABLE "MITKC_IRB_ATTACHMENT_STATUS" ADD CONSTRAINT "MITKC_IRB_ATTACHMENT_STATUS_PK" PRIMARY KEY ("STATUS_CD")
/
CREATE TABLE "MITKC_IRB_PROTOCOL_ORG_TYPE" 
(	
"PROTOCOL_ORG_TYPE_CODE" VARCHAR2(3 BYTE), 
"DESCRIPTION" VARCHAR2(200 BYTE) NOT NULL, 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL 
)
/
CREATE UNIQUE INDEX "MITKC_IRB_PROTOCOL_ORG_TYPE_PK" ON "MITKC_IRB_PROTOCOL_ORG_TYPE" ("PROTOCOL_ORG_TYPE_CODE") 
/
ALTER TABLE "MITKC_IRB_PROTOCOL_ORG_TYPE" ADD CONSTRAINT "MITKC_IRB_PROTOCOL_ORG_TYPE_PK" PRIMARY KEY ("PROTOCOL_ORG_TYPE_CODE")
/
CREATE TABLE "MITKC_IRB_ATTACHMENT_TYPE" 
(	
"TYPE_CD" VARCHAR2(3 BYTE), 
"DESCRIPTION" VARCHAR2(300 BYTE),
"UPDATE_TIMESTAMP" DATE, 
"UPDATE_USER" VARCHAR2(60 BYTE)
)
/
CREATE UNIQUE INDEX "MITKC_IRB_ATTACHMENT_TYPE_PK" ON "MITKC_IRB_ATTACHMENT_TYPE" ("TYPE_CD") 
/
ALTER TABLE "MITKC_IRB_ATTACHMENT_TYPE" ADD CONSTRAINT "MITKC_IRB_ATTACHMENT_TYPE_PK" PRIMARY KEY ("TYPE_CD")
/
ALTER TABLE "MITKC_IRB_ATTACHMENT_TYPE" MODIFY ("UPDATE_USER" NOT NULL ENABLE)
/
ALTER TABLE "MITKC_IRB_ATTACHMENT_TYPE" MODIFY ("UPDATE_TIMESTAMP" NOT NULL ENABLE)
/
ALTER TABLE "MITKC_IRB_ATTACHMENT_TYPE" MODIFY ("DESCRIPTION" NOT NULL ENABLE)
/
CREATE TABLE "MITKC_IRB_REVIEWER_TYPE" 
(	
"REVIEWER_TYPE_CODE" VARCHAR2(3 BYTE), 
"DESCRIPTION" VARCHAR2(200 BYTE), 
"UPDATE_TIMESTAMP" DATE, 
"UPDATE_USER" VARCHAR2(60 BYTE)
)
/
CREATE UNIQUE INDEX "MITKC_IRB_REVIEWER_TYPE_PK" ON "MITKC_IRB_REVIEWER_TYPE" ("REVIEWER_TYPE_CODE") 
/
ALTER TABLE "MITKC_IRB_REVIEWER_TYPE" MODIFY ("UPDATE_USER" NOT NULL ENABLE)
/
ALTER TABLE "MITKC_IRB_REVIEWER_TYPE" MODIFY ("UPDATE_TIMESTAMP" NOT NULL ENABLE)
/
ALTER TABLE "MITKC_IRB_REVIEWER_TYPE" MODIFY ("DESCRIPTION" NOT NULL ENABLE)
/
ALTER TABLE "MITKC_IRB_REVIEWER_TYPE" ADD CONSTRAINT "MITKC_IRB_REVIEWER_TYPE_PK" PRIMARY KEY ("REVIEWER_TYPE_CODE")
/
CREATE TABLE "MITKC_IRB_PERSON_ROLE_MAPPING" 
(	
"ROLE_MAPPING_ID" NUMBER(12,0), 
"SOURCE_ROLE_ID" VARCHAR2(12 BYTE) NOT NULL, 
"TARGET_ROLE_ID" VARCHAR2(12 BYTE) NOT NULL, 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL 
)
/
CREATE INDEX "UQ_PERSON_MAPPING" ON "MITKC_IRB_PERSON_ROLE_MAPPING" ("SOURCE_ROLE_ID", "TARGET_ROLE_ID")
/ 
CREATE UNIQUE INDEX "MITKC_IRB_PERSON_ROLE_MAP_" ON "MITKC_IRB_PERSON_ROLE_MAPPING" ("ROLE_MAPPING_ID") 
/
ALTER TABLE "MITKC_IRB_PERSON_ROLE_MAPPING" ADD CONSTRAINT "MITKC_IRB_PERSON_ROLE_MAP_PK" PRIMARY KEY ("ROLE_MAPPING_ID")
/
ALTER TABLE "MITKC_IRB_PERSON_ROLE_MAPPING" ADD CONSTRAINT "MITKC_IRB_PERSON_ROLE_MAP_FK1" FOREIGN KEY ("SOURCE_ROLE_ID")
REFERENCES "MITKC_IRB_PERSON_ROLES" ("PROTOCOL_PERSON_ROLE_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PERSON_ROLE_MAPPING" ADD CONSTRAINT "MITKC_IRB_PERSON_ROLE_MAP_FK2" FOREIGN KEY ("TARGET_ROLE_ID")
REFERENCES "MITKC_IRB_PERSON_ROLES" ("PROTOCOL_PERSON_ROLE_ID") ENABLE
/
CREATE TABLE "MITKC_ATTACHMENT_TYPE_GROUP" 
(	
"TYPE_GROUP_ID" NUMBER(12,0), 
"TYPE_CD" VARCHAR2(3 BYTE) NOT NULL, 
"GROUP_CD" VARCHAR2(3 BYTE) NOT NULL, 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL
)
/
CREATE UNIQUE INDEX "MITKC_ATTACHMENT_TYPE_GROUP_PK" ON "MITKC_ATTACHMENT_TYPE_GROUP" ("TYPE_GROUP_ID") 
/
ALTER TABLE "MITKC_ATTACHMENT_TYPE_GROUP" ADD CONSTRAINT "MITKC_ATTACHMENT_TYPE_GROUP_PK" PRIMARY KEY ("TYPE_GROUP_ID")
/
ALTER TABLE "MITKC_ATTACHMENT_TYPE_GROUP" ADD CONSTRAINT "MITKC_ATTACHMENT_TYP_GROUP_FK1" FOREIGN KEY ("GROUP_CD")
REFERENCES "MITKC_IRB_PROTO_ATT_GROUP" ("GROUP_CD") ENABLE
/
ALTER TABLE "MITKC_ATTACHMENT_TYPE_GROUP" ADD CONSTRAINT "MITKC_ATTACHMENT_TYP_GROUP_FK2" FOREIGN KEY ("TYPE_CD")
REFERENCES "MITKC_IRB_ATTACHMENT_TYPE" ("TYPE_CD") ENABLE
/
CREATE TABLE "MITKC_IRB_CONTINGENCY" 
(	
"PROTOCOL_CONTINGENCY_CODE" VARCHAR2(4 BYTE), 
"DESCRIPTION" VARCHAR2(2000 BYTE), 
"UPDATE_TIMESTAMP" DATE, 
"UPDATE_USER" VARCHAR2(60 BYTE)
)
/
CREATE UNIQUE INDEX "MITKC_IRB_CONTINGENCY_PK" ON "MITKC_IRB_CONTINGENCY" ("PROTOCOL_CONTINGENCY_CODE") 
/
ALTER TABLE "MITKC_IRB_CONTINGENCY" ADD CONSTRAINT "MITKC_IRB_CONTINGENCY_PK" PRIMARY KEY ("PROTOCOL_CONTINGENCY_CODE")
/
ALTER TABLE "MITKC_IRB_CONTINGENCY" MODIFY ("UPDATE_USER" NOT NULL ENABLE)
/
ALTER TABLE "MITKC_IRB_CONTINGENCY" MODIFY ("UPDATE_TIMESTAMP" NOT NULL ENABLE)
/
ALTER TABLE "MITKC_IRB_CONTINGENCY" MODIFY ("DESCRIPTION" NOT NULL ENABLE)
/
-----------------------------------------------------------------------------------------------------------------------------------------------------------
 

-------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE "MITKC_IRB_PROTOCOL_STATUS"(	
"PROTOCOL_STATUS_CODE" VARCHAR2(3 BYTE), 
"DESCRIPTION" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
CONSTRAINT "MITKC_IRB_PROTOCOL_STATUS_PK" PRIMARY KEY ("PROTOCOL_STATUS_CODE")
)
/
CREATE TABLE "MITKC_IRB_PROTOCOL_ACTION_TYPE"(
"PROTOCOL_ACTION_TYPE_CODE" VARCHAR2(3 BYTE), 
"DESCRIPTION" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
"TRIGGER_SUBMISSION" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
"TRIGGER_CORRESPONDENCE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
"FINAL_ACTION_FOR_BATCH_CORRESP" VARCHAR2(1 BYTE) NOT NULL ENABLE,
"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
CONSTRAINT "MITKC_IRB_PROTO_ACTION_TYPE_PK" PRIMARY KEY ("PROTOCOL_ACTION_TYPE_CODE")
)
/
CREATE TABLE "MITKC_IRB_PROTOCOL_MODULES"(
"PROTOCOL_MODULE_CODE" VARCHAR2(5 BYTE), 
"DESCRIPTION" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
CONSTRAINT "MITKC_IRB_PROTOCOL_MODULES_PK" PRIMARY KEY ("PROTOCOL_MODULE_CODE")
)
/
CREATE TABLE "MITKC_IRB_PROTOCOL_CONTINGENCY"(
"PROTOCOL_CONTINGENCY_CODE" VARCHAR2(4 BYTE), 
"DESCRIPTION" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL ENABLE,
CONSTRAINT "MITKC_IRB_PROTO_CONTINGENCY_PK" PRIMARY KEY ("PROTOCOL_CONTINGENCY_CODE")
)
/
CREATE TABLE "MITKC_IRB_PROTOCOL"(
"PROTOCOL_ID" NUMBER(12,0), 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL ENABLE, 
"PROTOCOL_TYPE_CODE" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
"PROTOCOL_STATUS_CODE" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
"TITLE" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
"DESCRIPTION" VARCHAR2(2000 BYTE), 
"APPROVAL_DATE" DATE, 
"EXPIRATION_DATE" DATE, 
"LAST_APPROVAL_DATE" DATE, 
"FDA_APPLICATION_NUMBER" VARCHAR2(15 BYTE), 
"REFERENCE_NUMBER_1" VARCHAR2(50 BYTE), 
"REFERENCE_NUMBER_2" VARCHAR2(50 BYTE), 
"INITIAL_SUBMISSION_DATE" DATE, 
"ACTIVE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
"IS_LATEST" VARCHAR2(1 BYTE), 
"CREATE_TIMESTAMP" DATE, 
"CREATE_USER" VARCHAR2(60 BYTE), 
"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
CONSTRAINT "MITKC_IRB_PROTOCOL_P1" PRIMARY KEY ("PROTOCOL_ID"), 
CONSTRAINT "MITKC_IRB_PROTOCOL_FK1" FOREIGN KEY ("PROTOCOL_TYPE_CODE") REFERENCES "MITKC_IRB_PROTOCOL_TYPE" ("PROTOCOL_TYPE_CODE") ENABLE, 
CONSTRAINT "MITKC_IRB_PROTOCOL_FK2" FOREIGN KEY ("PROTOCOL_STATUS_CODE") REFERENCES "MITKC_IRB_PROTOCOL_STATUS" ("PROTOCOL_STATUS_CODE") ENABLE
)
/
CREATE INDEX "MITKC_IRB_PROTOCOL_UK1" ON "MITKC_IRB_PROTOCOL" ("PROTOCOL_NUMBER", "SEQUENCE_NUMBER")
/
CREATE TABLE "MITKC_IRB_PROTOCOL_PERSONS" 
(	
"PROTOCOL_PERSON_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0), 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE), 
"SEQUENCE_NUMBER" NUMBER(4,0), 
"PERSON_ID" VARCHAR2(40 BYTE), 
"PERSON_NAME" VARCHAR2(90 BYTE), 
"PROTOCOL_PERSON_ROLE_ID" VARCHAR2(12 BYTE), 
"NON_EMPLOYEE_FLAG"  VARCHAR2(1 BYTE), 
"AFFILIATION_TYPE_CODE" NUMBER(3,0), 
"UPDATE_TIMESTAMP" DATE, 
"UPDATE_USER" VARCHAR2(60 BYTE),
"COMMENTS" CLOB, 
"SSN" VARCHAR2(9 BYTE), 
"LAST_NAME" VARCHAR2(30 BYTE), 
"FIRST_NAME" VARCHAR2(30 BYTE), 
"MIDDLE_NAME" VARCHAR2(30 BYTE), 
"FULL_NAME" VARCHAR2(90 BYTE), 
"PRIOR_NAME" VARCHAR2(30 BYTE), 
"USER_NAME" VARCHAR2(60 BYTE), 
"EMAIL_ADDRESS" VARCHAR2(60 BYTE), 
"DATE_OF_BIRTH" DATE, 
"AGE" NUMBER(3,0), 
"AGE_BY_FISCAL_YEAR" NUMBER(3,0), 
"GENDER" VARCHAR2(30 BYTE), 
"RACE" VARCHAR2(30 BYTE), 
"EDUCATION_LEVEL" VARCHAR2(30 BYTE), 
"DEGREE" VARCHAR2(11 BYTE), 
"MAJOR" VARCHAR2(30 BYTE), 
"IS_HANDICAPPED" CHAR(1 BYTE), 
"HANDICAP_TYPE" VARCHAR2(30 BYTE), 
"IS_VETERAN" CHAR(1 BYTE), 
"VETERAN_TYPE" VARCHAR2(30 BYTE), 
"VISA_CODE" VARCHAR2(20 BYTE), 
"VISA_TYPE" VARCHAR2(30 BYTE), 
"VISA_RENEWAL_DATE" DATE, 
"HAS_VISA" CHAR(1 BYTE), 
"OFFICE_LOCATION" VARCHAR2(30 BYTE), 
"OFFICE_PHONE" VARCHAR2(20 BYTE), 
"SECONDRY_OFFICE_LOCATION" VARCHAR2(30 BYTE), 
"SECONDRY_OFFICE_PHONE" VARCHAR2(20 BYTE), 
"SCHOOL" VARCHAR2(50 BYTE), 
"YEAR_GRADUATED" VARCHAR2(30 BYTE), 
"DIRECTORY_DEPARTMENT" VARCHAR2(30 BYTE), 
"SALUTATION" VARCHAR2(30 BYTE), 
"COUNTRY_OF_CITIZENSHIP" VARCHAR2(30 BYTE), 
"PRIMARY_TITLE" VARCHAR2(51 BYTE), 
"DIRECTORY_TITLE" VARCHAR2(50 BYTE), 
"HOME_UNIT" VARCHAR2(8 BYTE), 
"IS_FACULTY" CHAR(1 BYTE), 
"IS_GRADUATE_STUDENT_STAFF" CHAR(1 BYTE), 
"IS_RESEARCH_STAFF" CHAR(1 BYTE), 
"IS_SERVICE_STAFF" CHAR(1 BYTE), 
"IS_SUPPORT_STAFF" CHAR(1 BYTE), 
"IS_OTHER_ACCADEMIC_GROUP" CHAR(1 BYTE), 
"IS_MEDICAL_STAFF" CHAR(1 BYTE), 
"VACATION_ACCURAL" CHAR(1 BYTE), 
"IS_ON_SABBATICAL" CHAR(1 BYTE), 
"ID_PROVIDED" VARCHAR2(30 BYTE), 
"ID_VERIFIED" VARCHAR2(30 BYTE), 
"ADDRESS_LINE_1" VARCHAR2(80 BYTE), 
"ADDRESS_LINE_2" VARCHAR2(80 BYTE), 
"ADDRESS_LINE_3" VARCHAR2(80 BYTE), 
"CITY" VARCHAR2(30 BYTE), 
"COUNTY" VARCHAR2(30 BYTE), 
"STATE" VARCHAR2(30 BYTE), 
"POSTAL_CODE" VARCHAR2(15 BYTE), 
"COUNTRY_CODE" CHAR(3 BYTE), 
"FAX_NUMBER" VARCHAR2(20 BYTE), 
"PAGER_NUMBER" VARCHAR2(20 BYTE), 
"MOBILE_PHONE_NUMBER" VARCHAR2(20 BYTE), 
"ERA_COMMONS_USER_NAME" VARCHAR2(20 BYTE)
)
/
CREATE UNIQUE INDEX "MITKC_IRB_PROTOCOL_PERSONS_PK" ON "MITKC_IRB_PROTOCOL_PERSONS" ("PROTOCOL_PERSON_ID") 
/
CREATE INDEX "MITKC_IRB_PROTOCOL_PERSON_IDX1" ON "MITKC_IRB_PROTOCOL_PERSONS" ("PROTOCOL_ID") 
/
CREATE INDEX "MITKC_IRB_PROTOCOL_PERSON_IDX2" ON "MITKC_IRB_PROTOCOL_PERSONS" ("PROTOCOL_ID", "PROTOCOL_PERSON_ROLE_ID") 
/
ALTER TABLE "MITKC_IRB_PROTOCOL_PERSONS" MODIFY ("PERSON_NAME" NOT NULL ENABLE)
/
ALTER TABLE "MITKC_IRB_PROTOCOL_PERSONS" MODIFY ("SEQUENCE_NUMBER" NOT NULL ENABLE)
/
ALTER TABLE "MITKC_IRB_PROTOCOL_PERSONS" MODIFY ("PROTOCOL_NUMBER" NOT NULL ENABLE)
/
ALTER TABLE "MITKC_IRB_PROTOCOL_PERSONS" MODIFY ("PROTOCOL_ID" NOT NULL ENABLE)
/
ALTER TABLE "MITKC_IRB_PROTOCOL_PERSONS" ADD CONSTRAINT "MITKC_IRB_PROTOCOL_PERSONS_PK" PRIMARY KEY ("PROTOCOL_PERSON_ID")
/
ALTER TABLE "MITKC_IRB_PROTOCOL_PERSONS" ADD CONSTRAINT "MITKC_IRB_PROTOCOL_PERSONS_FK1" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_PERSONS" ADD CONSTRAINT "MITKC_IRB_PROTOCOL_PERSONS_FK3" FOREIGN KEY ("AFFILIATION_TYPE_CODE")
REFERENCES "AFFILIATION_TYPE" ("AFFILIATION_TYPE_CODE") ENABLE
/  

CREATE TABLE "MITKC_IRB_PROTOCOL_UNITS" 
(	
"PROTOCOL_UNITS_ID" NUMBER(12,0), 
"PROTOCOL_PERSON_ID" NUMBER(12,0)NOT NULL, 
"PROTOCOL_ID" NUMBER(12,0), 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE), 
"SEQUENCE_NUMBER" NUMBER(4,0), 
"PERSON_ID" VARCHAR2(40 BYTE), 
"UNIT_NUMBER" VARCHAR2(8 BYTE)NOT NULL, 
"LEAD_UNIT_FLAG" VARCHAR2(1 BYTE) NOT NULL, 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL
)
/
CREATE UNIQUE INDEX "MITKC_IRB_PROTOCOL_UNITS_PK" ON "MITKC_IRB_PROTOCOL_UNITS" ("PROTOCOL_UNITS_ID") 
/
CREATE INDEX "MITKC_IRB_PROTOCOL_UNITS_UK1" ON "MITKC_IRB_PROTOCOL_UNITS" ("UNIT_NUMBER", "PERSON_ID", "PROTOCOL_PERSON_ID") 
/
ALTER TABLE "MITKC_IRB_PROTOCOL_UNITS" ADD CONSTRAINT "MITKC_IRB_PROTOCOL_UNITS_PK" PRIMARY KEY ("PROTOCOL_UNITS_ID")
/
ALTER TABLE "MITKC_IRB_PROTOCOL_UNITS" ADD CONSTRAINT "MITKC_IRB_PROTOCOL_UNITS_FK1" FOREIGN KEY ("UNIT_NUMBER")
REFERENCES "UNIT" ("UNIT_NUMBER") ENABLE
/
CREATE TABLE "MITKC_IRB_PROTOCOL_REFERENCES" 
(	
"PROTOCOL_REFERENCE_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0), 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"PROTOCOL_REFERENCE_NUMBER" NUMBER(12,0) NOT NULL, 
"PROTOCOL_REFERENCE_TYPE_CODE" NUMBER(3,0) NOT NULL, 
"REFERENCE_KEY" VARCHAR2(50 BYTE) NOT NULL, 
"APPLICATION_DATE" DATE, 
"APPROVAL_DATE" DATE, 
"COMMENTS" CLOB, 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL
)
/
CREATE UNIQUE INDEX "MITKC_IRB_PROTO_REFERENCES_PK" ON "MITKC_IRB_PROTOCOL_REFERENCES" ("PROTOCOL_REFERENCE_ID") 
/
ALTER TABLE "MITKC_IRB_PROTOCOL_REFERENCES" ADD CONSTRAINT "MITKC_IRB_PROTO_REFERENCES_PK" PRIMARY KEY ("PROTOCOL_REFERENCE_ID")
/
ALTER TABLE "MITKC_IRB_PROTOCOL_REFERENCES" ADD CONSTRAINT "MITKC_IRB_PROTO_REFERENCES_FK1" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_REFERENCES" ADD CONSTRAINT "MITKC_IRB_PROTO_REFERENCES_FK2" FOREIGN KEY ("PROTOCOL_REFERENCE_TYPE_CODE")
REFERENCES "MITKC_IRB_PROTO_REFERENCE_TYPE" ("PROTOCOL_REFERENCE_TYPE_CODE") ENABLE
/ 
CREATE TABLE "MITKC_IRB_ONLN_RVW_DETRM_RECOM" 
(	
"REVIEW_DETERM_RECOM_CD" NUMBER(3,0), 
"DESCRIPTION" VARCHAR2(200 BYTE) NOT NULL, 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL
)
/
CREATE UNIQUE INDEX "MITKC_IRB_ONLN_RVW_DETRM_R_PK" ON "MITKC_IRB_ONLN_RVW_DETRM_RECOM" ("REVIEW_DETERM_RECOM_CD") 
/
ALTER TABLE "MITKC_IRB_ONLN_RVW_DETRM_RECOM" ADD CONSTRAINT "MITKC_IRB_ONLN_RVW_DETRM_R_PK" PRIMARY KEY ("REVIEW_DETERM_RECOM_CD")
/
CREATE TABLE "MITKC_IRB_ONLN_RVW_STATUS" 
(	
"STATUS_CODE" VARCHAR2(3 BYTE), 
"DESCRIPTION" VARCHAR2(200 BYTE) NOT NULL, 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL
)
/
CREATE UNIQUE INDEX "MITKC_IRB_ONLN_RVW_STATUS_PK" ON "MITKC_IRB_ONLN_RVW_STATUS" ("STATUS_CODE") 
/
ALTER TABLE "MITKC_IRB_ONLN_RVW_STATUS" ADD CONSTRAINT "MITKC_IRB_ONLN_RVW_STATUS_PK" PRIMARY KEY ("STATUS_CODE")
/
--------------------------------------------------------------------------------------------------------

--------------------------------------------------------
--  DDL for Table MITKC_IRB_PROTOCOL_SUBMISSION
--------------------------------------------------------
CREATE TABLE "MITKC_IRB_PROTOCOL_SUBMISSION" 
(	
"SUBMISSION_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL, 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"SUBMISSION_NUMBER" NUMBER(4,0) NOT NULL, 
"SCHEDULE_ID" VARCHAR2(10 BYTE), 
"COMMITTEE_ID" VARCHAR2(15 BYTE), 
"SUBMISSION_TYPE_CODE" VARCHAR2(3 BYTE) NOT NULL, 
"SUBMISSION_TYPE_QUAL_CODE" VARCHAR2(3 BYTE), 
"SUBMISSION_STATUS_CODE" VARCHAR2(3 BYTE) NOT NULL, 
"PROTOCOL_REVIEW_TYPE_CODE" VARCHAR2(3 BYTE) NOT NULL, 
"SUBMISSION_DATE" DATE NOT NULL, 
"COMMENTS" VARCHAR2(4000 BYTE), 
"YES_VOTE_COUNT" NUMBER(3,0), 
"NO_VOTE_COUNT" NUMBER(3,0), 
"ABSTAINER_COUNT" NUMBER(3,0), 
"VOTING_COMMENTS" VARCHAR2(2000 BYTE), 
"UPDATE_TIMESTAMP" DATE, 
"UPDATE_USER" VARCHAR2(60 BYTE),
"RECUSED_COUNT" NUMBER(3,0), 
"IS_BILLABLE" VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL, 
"COMM_DECISION_MOTION_TYPE_CODE" VARCHAR2(3 BYTE)
)
/
CREATE UNIQUE INDEX "MITKC_IRB_PROTO_SUBMISSION_PK" ON "MITKC_IRB_PROTOCOL_SUBMISSION" ("SUBMISSION_ID") 
/
CREATE INDEX "PROTOCOL_SUBMISSION_IDX" ON "MITKC_IRB_PROTOCOL_SUBMISSION" ("PROTOCOL_ID") 
/
CREATE INDEX "PROTOCOL_SUBMISSION_IDX2" ON "MITKC_IRB_PROTOCOL_SUBMISSION" ("PROTOCOL_NUMBER") 
/
CREATE INDEX "MITKC_IRB_PROT_SUBMISSION_IDX1" ON "MITKC_IRB_PROTOCOL_SUBMISSION" ("PROTOCOL_ID", "SUBMISSION_NUMBER") 
/
ALTER TABLE "MITKC_IRB_PROTOCOL_SUBMISSION" ADD CONSTRAINT "MITKC_IRB_PROTO_SUBMISSION_PK" PRIMARY KEY ("SUBMISSION_ID")
/
ALTER TABLE "MITKC_IRB_PROTOCOL_SUBMISSION" ADD CONSTRAINT "MITKC_IRB_PROTO_SUBMISSION_FK1" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_SUBMISSION" ADD CONSTRAINT "MITKC_IRB_PROTO_SUBMISSION_FK4" FOREIGN KEY ("PROTOCOL_REVIEW_TYPE_CODE")
REFERENCES "MITKC_IRB_PROTOCOL_REVIEW_TYPE" ("PROTOCOL_REVIEW_TYPE_CODE") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_SUBMISSION" ADD CONSTRAINT "MITKC_IRB_PROTO_SUBMISSION_FK5" FOREIGN KEY ("SUBMISSION_STATUS_CODE")
REFERENCES "SUBMISSION_STATUS" ("SUBMISSION_STATUS_CODE") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_SUBMISSION" ADD CONSTRAINT "MITKC_IRB_PROTO_SUBMISSION_FK6" FOREIGN KEY ("SUBMISSION_TYPE_CODE")
REFERENCES "SUBMISSION_TYPE" ("SUBMISSION_TYPE_CODE") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_SUBMISSION" ADD CONSTRAINT "MITKC_IRB_PROTO_SUBMISSION_FK7" FOREIGN KEY ("SUBMISSION_TYPE_QUAL_CODE")
REFERENCES "SUBMISSION_TYPE_QUALIFIER" ("SUBMISSION_TYPE_QUAL_CODE") ENABLE
/

--------------------------------------------------------
--  DDL for Table MITKC_IRB_PROTOCOL_REVIEWERS
--------------------------------------------------------
CREATE TABLE "MITKC_IRB_PROTOCOL_REVIEWERS" 
(	
"PROTOCOL_REVIEWER_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL, 
"SUBMISSION_ID" NUMBER(12,0) NOT NULL, 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"SUBMISSION_NUMBER" NUMBER(4,0) NOT NULL, 
"PERSON_ID" VARCHAR2(40 BYTE), 
"NON_EMPLOYEE_FLAG" VARCHAR2(1 BYTE) NOT NULL, 
"REVIEWER_TYPE_CODE" VARCHAR2(3 BYTE) NOT NULL, 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL
)
/
CREATE UNIQUE INDEX "MITKC_IRB_PROTO_REVIEWES_PK" ON "MITKC_IRB_PROTOCOL_REVIEWERS" ("PROTOCOL_REVIEWER_ID") 
/
ALTER TABLE "MITKC_IRB_PROTOCOL_REVIEWERS" ADD CONSTRAINT "MITKC_IRB_PROTO_REVIEWES_PK" PRIMARY KEY ("PROTOCOL_REVIEWER_ID")
/
ALTER TABLE "MITKC_IRB_PROTOCOL_REVIEWERS" ADD CONSTRAINT "MITKC_IRB_PROTO_REVIEWES_FK1" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_REVIEWERS" ADD CONSTRAINT "MITKC_IRB_PROTO_REVIEWES_FK2" FOREIGN KEY ("SUBMISSION_ID")
REFERENCES "MITKC_IRB_PROTOCOL_SUBMISSION" ("SUBMISSION_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_REVIEWERS" ADD CONSTRAINT "MITKC_IRB_PROTO_REVIEWES_FK3" FOREIGN KEY ("REVIEWER_TYPE_CODE")
REFERENCES "MITKC_IRB_REVIEWER_TYPE" ("REVIEWER_TYPE_CODE") ENABLE
/
CREATE TABLE "MITKC_IRB_PROTOCOL_ONLN_RVWS" 
(	
"PROTOCOL_ONLN_RVW_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL, 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"SUBMISSION_ID" NUMBER(12,0) NOT NULL, 
"PROTOCOL_REVIEWER_ID" NUMBER(12,0) NOT NULL, 
"PROTOCOL_ONLN_RVW_STATUS_CODE" VARCHAR2(3 BYTE), 
"REVIEW_DETERM_RECOM_CD" NUMBER(3,0), 
"DATE_REQUESTED" DATE, 
"DATE_DUE" DATE, 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL,
"ACTIONS_PERFORMED" VARCHAR2(1000 BYTE), 
"REVIEWER_APPROVED" VARCHAR2(1 BYTE), 
"ADMIN_ACCEPTED" VARCHAR2(1 BYTE)
)
/
CREATE UNIQUE INDEX "UQ1_PROTOCOL_ONLN_RVWS" ON "MITKC_IRB_PROTOCOL_ONLN_RVWS" ("PROTOCOL_ID", "SUBMISSION_ID", "PROTOCOL_REVIEWER_ID") 
/
CREATE UNIQUE INDEX "MITKC_IRB_PROTO_ONLN_RVWS_PK" ON "MITKC_IRB_PROTOCOL_ONLN_RVWS" ("PROTOCOL_ONLN_RVW_ID") 
/
CREATE INDEX "MITKC_IRB_PROTO_ONLN_RVWS_IDX1" ON "MITKC_IRB_PROTOCOL_ONLN_RVWS" ("PROTOCOL_ID") 
/
ALTER TABLE "MITKC_IRB_PROTOCOL_ONLN_RVWS" ADD CONSTRAINT "MITKC_IRB_PROTO_ONLN_RVWS_PK" PRIMARY KEY ("PROTOCOL_ONLN_RVW_ID")
/
ALTER TABLE "MITKC_IRB_PROTOCOL_ONLN_RVWS" ADD CONSTRAINT "MITKC_IRB_PROTO_ONLN_RVWS_UK1" UNIQUE ("PROTOCOL_ID", "SUBMISSION_ID", "PROTOCOL_REVIEWER_ID")
/
ALTER TABLE "MITKC_IRB_PROTOCOL_ONLN_RVWS" ADD CONSTRAINT "MITKC_IRB_PROTO_ONLN_RVWS_FK1" FOREIGN KEY ("PROTOCOL_ONLN_RVW_STATUS_CODE")
REFERENCES "MITKC_IRB_ONLN_RVW_STATUS" ("STATUS_CODE") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_ONLN_RVWS" ADD CONSTRAINT "MITKC_IRB_PROTO_ONLN_RVWS_FK2" FOREIGN KEY ("PROTOCOL_REVIEWER_ID")
REFERENCES "MITKC_IRB_PROTOCOL_REVIEWERS" ("PROTOCOL_REVIEWER_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_ONLN_RVWS" ADD CONSTRAINT "MITKC_IRB_PROTO_ONLN_RVWS_FK3" FOREIGN KEY ("SUBMISSION_ID")
REFERENCES "MITKC_IRB_PROTOCOL_SUBMISSION" ("SUBMISSION_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_ONLN_RVWS" ADD CONSTRAINT "MITKC_IRB_PROTO_ONLN_RVWS_FK4" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_ONLN_RVWS" ADD CONSTRAINT "MITKC_IRB_PROTO_ONLN_RVWS_FK5" FOREIGN KEY ("REVIEW_DETERM_RECOM_CD")
REFERENCES "MITKC_IRB_ONLN_RVW_DETRM_RECOM" ("REVIEW_DETERM_RECOM_CD") ENABLE
/
--------------------------------------------------------
--  DDL for Table MITKC_IRB_PROTOCOL_ORG_TYPE
--------------------------------------------------------

CREATE TABLE "MITKC_IRB_PROTOCOL_LOCATION" 
(	
"PROTOCOL_LOCATION_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL, 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"PROTOCOL_ORG_TYPE_CODE" VARCHAR2(3 BYTE) NOT NULL, 
"ORGANIZATION_ID" VARCHAR2(8 BYTE) NOT NULL, 
"ROLODEX_ID" NUMBER(6,0), 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL
)
/
CREATE UNIQUE INDEX "MITKC_IRB_PROTO_LOCATION_PK" ON "MITKC_IRB_PROTOCOL_LOCATION" ("PROTOCOL_LOCATION_ID") 
/
CREATE INDEX "UQ_PROTOCOL_LOCATION" ON "MITKC_IRB_PROTOCOL_LOCATION" ("PROTOCOL_ORG_TYPE_CODE", "ORGANIZATION_ID", "PROTOCOL_ID") 
/
ALTER TABLE "MITKC_IRB_PROTOCOL_LOCATION" ADD CONSTRAINT "MITKC_IRB_PROTO_LOCATION_PK" PRIMARY KEY ("PROTOCOL_LOCATION_ID")
/
ALTER TABLE "MITKC_IRB_PROTOCOL_LOCATION" ADD CONSTRAINT "MITKC_IRB_PROTO_LOCATION_FK1" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_LOCATION" ADD CONSTRAINT "MITKC_IRB_PROTO_LOCATION_FK2" FOREIGN KEY ("ORGANIZATION_ID")
REFERENCES "ORGANIZATION" ("ORGANIZATION_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_LOCATION" ADD CONSTRAINT "MITKC_IRB_PROTO_LOCATION_FK3" FOREIGN KEY ("PROTOCOL_ORG_TYPE_CODE")
REFERENCES "MITKC_IRB_PROTOCOL_ORG_TYPE" ("PROTOCOL_ORG_TYPE_CODE") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_LOCATION" ADD CONSTRAINT "MITKC_IRB_PROTO_LOCATION_FK4" FOREIGN KEY ("ROLODEX_ID")
REFERENCES "ROLODEX" ("ROLODEX_ID") ENABLE
/

--------------------------------------------------------
--  DDL for Table MITKC_IRB_PROTOCOL_RISK_LEVELS
--------------------------------------------------------
CREATE TABLE "MITKC_IRB_PROTOCOL_RISK_LEVELS" 
(	
"PROTOCOL_RISK_LEVELS_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL,
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"RISK_LEVEL_CODE" VARCHAR2(3 BYTE) NOT NULL, 
"COMMENTS" VARCHAR2(2000 BYTE), 
"DATE_ASSIGNED" DATE, 
"DATE_INACTIVATED" DATE NOT NULL, 
"STATUS" VARCHAR2(1 BYTE) NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL, 
"UPDATE_TIMESTAMP" DATE NOT NULL
)
/
CREATE UNIQUE INDEX "MITKC_IRB_PROTO_RISK_LEVELS_PK" ON "MITKC_IRB_PROTOCOL_RISK_LEVELS" ("PROTOCOL_RISK_LEVELS_ID") 
/
CREATE INDEX "UQ_PROTOCOL_RISK_LEVELS" ON "MITKC_IRB_PROTOCOL_RISK_LEVELS" ("PROTOCOL_NUMBER", "SEQUENCE_NUMBER", "RISK_LEVEL_CODE") 
/
ALTER TABLE "MITKC_IRB_PROTOCOL_RISK_LEVELS" ADD CONSTRAINT "MITKC_IRB_PROTO_RISK_LEVELS_PK" PRIMARY KEY ("PROTOCOL_RISK_LEVELS_ID")
/
ALTER TABLE "MITKC_IRB_PROTOCOL_RISK_LEVELS" ADD CONSTRAINT "FK_PROTOCOL_RISK_LEVELS" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_RISK_LEVELS" ADD CONSTRAINT "FK_PROTOCOL_RISK_LEVELS2" FOREIGN KEY ("RISK_LEVEL_CODE")
REFERENCES "RISK_LEVEL" ("RISK_LEVEL_CODE") ENABLE
/
--------------------------------------------------------
--  DDL for Table MITKC_IRB_PROTOCOL_ACTIONS
--------------------------------------------------------
CREATE TABLE "MITKC_IRB_PROTOCOL_ACTIONS" 
(	
"PROTOCOL_ACTION_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL, 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"SUBMISSION_NUMBER" NUMBER(4,0), 
"ACTION_ID" NUMBER(6,0) NOT NULL, 
"PROTOCOL_ACTION_TYPE_CODE" VARCHAR2(3 BYTE) NOT NULL, 
"SUBMISSION_ID" NUMBER(12,0), 
"COMMENTS" VARCHAR2(2000 BYTE), 
"ACTION_DATE" DATE, 
"UPDATE_TIMESTAMP" DATE, 
"UPDATE_USER" VARCHAR2(60 BYTE),
"ACTUAL_ACTION_DATE" DATE,  
"PREV_SUBMISSION_STATUS_CODE" VARCHAR2(3 BYTE), 
"SUBMISSION_TYPE_CODE" VARCHAR2(3 BYTE), 
"PREV_PROTOCOL_STATUS_CODE" VARCHAR2(3 BYTE), 
"FOLLOWUP_ACTION_CODE" VARCHAR2(3 BYTE), 
"CREATE_USER" VARCHAR2(60 BYTE), 
"CREATE_TIMESTAMP" DATE
)
/
CREATE INDEX "MITKC_IRB_PROTO_ACTIONS_IDX1" ON "MITKC_IRB_PROTOCOL_ACTIONS" ("PROTOCOL_ID") 
/
CREATE INDEX "MITKC_IRB_PROTO_ACTIONS_IDX2" ON "MITKC_IRB_PROTOCOL_ACTIONS" ("PROTOCOL_NUMBER", "SEQUENCE_NUMBER") 
/
CREATE INDEX "MITKC_IRB_PROTO_ACTIONS_IDX3" ON "MITKC_IRB_PROTOCOL_ACTIONS" ("SUBMISSION_ID") 
/
CREATE UNIQUE INDEX "MITKC_IRB_PROTO_ACTIONS_PK" ON "MITKC_IRB_PROTOCOL_ACTIONS" ("PROTOCOL_ACTION_ID") 
/
ALTER TABLE "MITKC_IRB_PROTOCOL_ACTIONS" ADD CONSTRAINT "MITKC_IRB_PROTO_ACTIONS_PK" PRIMARY KEY ("PROTOCOL_ACTION_ID")
/
ALTER TABLE "MITKC_IRB_PROTOCOL_ACTIONS" ADD CONSTRAINT "MITKC_IRB_PROTO_ACTIONS_FK1" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_ACTIONS" ADD CONSTRAINT "MITKC_IRB_PROTO_ACTIONS_FK2" FOREIGN KEY ("SUBMISSION_ID")
REFERENCES "MITKC_IRB_PROTOCOL_SUBMISSION" ("SUBMISSION_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTOCOL_ACTIONS" ADD CONSTRAINT "MITKC_IRB_PROTO_ACTIONS_FK3" FOREIGN KEY ("PROTOCOL_ACTION_TYPE_CODE")
REFERENCES "MITKC_IRB_PROTOCOL_ACTION_TYPE" ("PROTOCOL_ACTION_TYPE_CODE") ENABLE
/
--------------------------------------------------------
--  DDL for Table MITKC_IRB_ATTACHMENT_TYPE
--------------------------------------------------------
CREATE TABLE "MITKC_IRB_ATTACHMENT" 
(	
  	"FILE_ID" NUMBER(22,0), 
	"FILE_NAME" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"FILE_DATA" BLOB, 
	"CONTENT_TYPE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE, 
	"UPDATE_USER" VARCHAR2(8 BYTE), 
	 CONSTRAINT "MITKC_IRB_ATTACHMENT_PK" PRIMARY KEY ("FILE_ID")
)
/
CREATE TABLE "MITKC_IRB_ATTACHMENT_PROTOCOL" 
(	
"PA_PROTOCOL_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL, 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"TYPE_CD" VARCHAR2(3 BYTE) NOT NULL, 
"DOCUMENT_ID" NUMBER(4,0) NOT NULL, 
"FILE_ID" NUMBER(22,0) NOT NULL, 
"DESCRIPTION" VARCHAR2(200 BYTE), 
"STATUS_CD" VARCHAR2(3 BYTE), 
"CONTACT_NAME" VARCHAR2(30 BYTE), 
"EMAIL_ADDRESS" VARCHAR2(60 BYTE), 
"PHONE_NUMBER" VARCHAR2(20 BYTE), 
"COMMENTS" VARCHAR2(300 BYTE), 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL, 
"DOCUMENT_STATUS_CODE" VARCHAR2(3 BYTE), 
"CREATE_TIMESTAMP" DATE NOT NULL, 
"ATTACHMENT_VERSION" NUMBER(4,0)
)
/
CREATE INDEX "MITKC_IRB_ATT_PROTOCOL_IDX1" ON "MITKC_IRB_ATTACHMENT_PROTOCOL" ("FILE_ID") 
/
CREATE INDEX "MITKC_IRB_ATT_PROTOCOL_IDX2" ON "MITKC_IRB_ATTACHMENT_PROTOCOL" ("PROTOCOL_ID") 
/
CREATE UNIQUE INDEX "MITKC_IRB_ATT_PROTOCOL_PK" ON "MITKC_IRB_ATTACHMENT_PROTOCOL" ("PA_PROTOCOL_ID") 
/
ALTER TABLE "MITKC_IRB_ATTACHMENT_PROTOCOL" ADD CONSTRAINT "MITKC_IRB_ATT_PROTOCOL_PK" PRIMARY KEY ("PA_PROTOCOL_ID")
/
ALTER TABLE "MITKC_IRB_ATTACHMENT_PROTOCOL" ADD CONSTRAINT "MITKC_IRB_ATT_PROTOCOL_FK2" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_ATTACHMENT_PROTOCOL" ADD CONSTRAINT "MITKC_IRB_ATT_PROTOCOL_FK3" FOREIGN KEY ("TYPE_CD")
REFERENCES "MITKC_IRB_ATTACHMENT_TYPE" ("TYPE_CD") ENABLE
/
ALTER TABLE "MITKC_IRB_ATTACHMENT_PROTOCOL" ADD CONSTRAINT "MITKC_IRB_ATT_PROTOCOL_FK4" FOREIGN KEY ("STATUS_CD")
REFERENCES "MITKC_IRB_ATTACHMENT_STATUS" ("STATUS_CD") ENABLE
/

--------------------------------------------------------
--  DDL for Table MITKC_IRB_PROTOCOL_UNITS
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Table MITKC_IRB_PROTO_FUNDING_SOURCE
--------------------------------------------------------
CREATE TABLE "MITKC_IRB_PROTO_FUNDING_SOURCE" 
(	
"PROTOCOL_FUNDING_SOURCE_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL, 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"FUNDING_SOURCE_TYPE_CODE" VARCHAR2(3 BYTE) NOT NULL, 
"FUNDING_SOURCE" VARCHAR2(200 BYTE) NOT NULL, 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL, 
"FUNDING_SOURCE_NAME" VARCHAR2(200 BYTE)
)
/
CREATE INDEX "MITKC_IRB_FUNDING_SOURCE_IDX1" ON "MITKC_IRB_PROTO_FUNDING_SOURCE" ("PROTOCOL_ID", "FUNDING_SOURCE_TYPE_CODE", "FUNDING_SOURCE") 
/
CREATE UNIQUE INDEX "MITKC_IRB_FUNDING_SOURCE_PK" ON "MITKC_IRB_PROTO_FUNDING_SOURCE" ("PROTOCOL_FUNDING_SOURCE_ID") 
/
ALTER TABLE "MITKC_IRB_PROTO_FUNDING_SOURCE" ADD CONSTRAINT "MITKC_IRB_FUNDING_SOURCE_PK" PRIMARY KEY ("PROTOCOL_FUNDING_SOURCE_ID")
/
ALTER TABLE "MITKC_IRB_PROTO_FUNDING_SOURCE" ADD CONSTRAINT "MITKC_IRB_FUNDING_SOURCE_FK1" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTO_FUNDING_SOURCE" ADD CONSTRAINT "MITKC_IRB_FUNDING_SOURCE_FK2" FOREIGN KEY ("FUNDING_SOURCE_TYPE_CODE")
REFERENCES "FUNDING_SOURCE_TYPE" ("FUNDING_SOURCE_TYPE_CODE") ENABLE
/
--------------------------------------------------------
--  DDL for Table MITKC_IRB_ATTACHMENT_PERSONNEL
--------------------------------------------------------
CREATE TABLE "MITKC_IRB_ATTACHMENT_PERSONNEL" 
(	
"PA_PERSONNEL_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL, 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"TYPE_CD" VARCHAR2(3 BYTE) NOT NULL, 
"DOCUMENT_ID" NUMBER(4,0) NOT NULL, 
"FILE_ID" NUMBER(22,0) NOT NULL, 
"DESCRIPTION" VARCHAR2(200 BYTE), 
"PERSON_ID" NUMBER(12,0),
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL
)
/
CREATE INDEX "MITKC_IRB_ATTA_PERSONNEL_IDX1" ON "MITKC_IRB_ATTACHMENT_PERSONNEL" ("FILE_ID") 
/
CREATE INDEX "MITKC_IRB_ATTA_PERSONNEL_IDX2" ON "MITKC_IRB_ATTACHMENT_PERSONNEL" ("PROTOCOL_ID") 
/
CREATE UNIQUE INDEX "MITKC_IRB_ATTA_PERSONNEL_PK" ON "MITKC_IRB_ATTACHMENT_PERSONNEL" ("PA_PERSONNEL_ID") 
/
ALTER TABLE "MITKC_IRB_ATTACHMENT_PERSONNEL" ADD CONSTRAINT "MITKC_IRB_ATTA_PERSONNEL_PK" PRIMARY KEY ("PA_PERSONNEL_ID")
/
ALTER TABLE "MITKC_IRB_ATTACHMENT_PERSONNEL" ADD CONSTRAINT "MITKC_IRB_ATTA_PERSONNEL_FK1" FOREIGN KEY ("FILE_ID")
REFERENCES "ATTACHMENT_FILE" ("FILE_ID") DISABLE
/
ALTER TABLE "MITKC_IRB_ATTACHMENT_PERSONNEL" ADD CONSTRAINT "MITKC_IRB_ATTA_PERSONNEL_FK2" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_ATTACHMENT_PERSONNEL" ADD CONSTRAINT "MITKC_IRB_ATTA_PERSONNEL_FK3" FOREIGN KEY ("TYPE_CD")
REFERENCES "MITKC_IRB_ATTACHMENT_TYPE" ("TYPE_CD") ENABLE
/
ALTER TABLE "MITKC_IRB_ATTACHMENT_PERSONNEL" ADD CONSTRAINT "MITKC_IRB_ATTA_PERSONNEL_FK4" FOREIGN KEY ("PERSON_ID")
REFERENCES "MITKC_IRB_PROTOCOL_PERSONS" ("PROTOCOL_PERSON_ID") ENABLE
/
--------------------------------------------------------
--  DDL for Table MITKC_IRB_PROTO_VOTE_RECUSED
--------------------------------------------------------
CREATE TABLE "MITKC_IRB_PROTO_VOTE_RECUSED" 
(	
"PROTOCOL_VOTE_RECUSED_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0), 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"SUBMISSION_ID" NUMBER(12,0), 
"PERSON_ID" VARCHAR2(40 BYTE), 
"ROLODEX_ID" NUMBER(6,0), 
"NON_EMPLOYEE_FLAG" VARCHAR2(1 BYTE) NOT NULL, 
"COMMENTS" VARCHAR2(2000 BYTE), 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL, 
"IACUC_PROTOCOL_ID" NUMBER(12,0), 
"IACUC_SUBMISSION_ID" NUMBER(12,0)
)
/
CREATE UNIQUE INDEX "MITKC_IRB_VOTE_RECUSED_UK1" ON "MITKC_IRB_PROTO_VOTE_RECUSED" ("PROTOCOL_VOTE_RECUSED_ID") 
/
ALTER TABLE "MITKC_IRB_PROTO_VOTE_RECUSED" ADD CONSTRAINT "MITKC_IRB_VOTE_RECUSED_PK" PRIMARY KEY ("PROTOCOL_VOTE_RECUSED_ID")
/
ALTER TABLE "MITKC_IRB_PROTO_VOTE_RECUSED" ADD CONSTRAINT "MITKC_IRB_VOTE_RECUSED_FK1" FOREIGN KEY ("ROLODEX_ID")
REFERENCES "ROLODEX" ("ROLODEX_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTO_VOTE_RECUSED" ADD CONSTRAINT "MITKC_IRB_VOTE_RECUSED_FK2" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTO_VOTE_RECUSED" ADD CONSTRAINT "MITKC_IRB_VOTE_RECUSED_FK3" FOREIGN KEY ("SUBMISSION_ID")
REFERENCES "MITKC_IRB_PROTOCOL_SUBMISSION" ("SUBMISSION_ID") ENABLE
/


--------------------------------------------------------
--  DDL for Table MITKC_IRB_PROTO_SPECIAL_REVIEW
--------------------------------------------------------
CREATE TABLE "MITKC_IRB_PROTO_SPECIAL_REVIEW" 
(	
"PROTOCOL_SPECIAL_REVIEW_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL,
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"SPECIAL_REVIEW_NUMBER" NUMBER(3,0) NOT NULL, 
"SPECIAL_REVIEW_CODE" NUMBER(3,0) NOT NULL, 
"APPROVAL_TYPE_CODE" NUMBER(3,0) NOT NULL,
"APPLICATION_DATE" DATE, 
"APPROVAL_DATE" DATE, 
"EXPIRATION_DATE" DATE, 
"COMMENTS" CLOB, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL, 
"UPDATE_TIMESTAMP" DATE NOT NULL
)
/
CREATE UNIQUE INDEX "MITKC_IRB_SPECIAL_REVIEW_UK1" ON "MITKC_IRB_PROTO_SPECIAL_REVIEW" ("PROTOCOL_SPECIAL_REVIEW_ID") 
/
ALTER TABLE "MITKC_IRB_PROTO_SPECIAL_REVIEW" ADD CONSTRAINT "MITKC_IRB_SPECIAL_REVIEW_PK" PRIMARY KEY ("PROTOCOL_SPECIAL_REVIEW_ID")
/
ALTER TABLE "MITKC_IRB_PROTO_SPECIAL_REVIEW" ADD CONSTRAINT "MITKC_IRB_SPECIAL_REVIEW_FK1" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
--------------------------------------------------------
--  DDL for Table MITKC_IRB_EXEMPT_NUMBER
--------------------------------------------------------
CREATE TABLE "MITKC_IRB_EXEMPT_NUMBER" 
(	
"PROTOCOL_EXEMPT_NUMBER_ID" NUMBER(12,0), 
"PROTOCOL_SPECIAL_REVIEW_ID" NUMBER(12,0), 
"EXEMPTION_TYPE_CODE" VARCHAR2(3 BYTE), 
"UPDATE_USER" VARCHAR2(60 BYTE), 
"UPDATE_TIMESTAMP" DATE
)
/
CREATE UNIQUE INDEX "MITKC_IRB_EXEMPT_NUMBER_PK" ON "MITKC_IRB_EXEMPT_NUMBER" ("PROTOCOL_EXEMPT_NUMBER_ID") 
/
ALTER TABLE "MITKC_IRB_EXEMPT_NUMBER" ADD CONSTRAINT "MITKC_IRB_EXEMPT_NUMBER_PK" PRIMARY KEY ("PROTOCOL_EXEMPT_NUMBER_ID")
/
ALTER TABLE "MITKC_IRB_EXEMPT_NUMBER" MODIFY ("UPDATE_TIMESTAMP" NOT NULL ENABLE)
/
ALTER TABLE "MITKC_IRB_EXEMPT_NUMBER" MODIFY ("UPDATE_USER" NOT NULL ENABLE)
/
ALTER TABLE "MITKC_IRB_EXEMPT_NUMBER" MODIFY ("EXEMPTION_TYPE_CODE" NOT NULL ENABLE)
/
ALTER TABLE "MITKC_IRB_EXEMPT_NUMBER" MODIFY ("PROTOCOL_SPECIAL_REVIEW_ID" NOT NULL ENABLE)
/
ALTER TABLE "MITKC_IRB_EXEMPT_NUMBER" ADD CONSTRAINT "MITKC_IRB_EXEMPT_NUMBER_FK1" FOREIGN KEY ("PROTOCOL_SPECIAL_REVIEW_ID")
REFERENCES "MITKC_IRB_PROTO_SPECIAL_REVIEW" ("PROTOCOL_SPECIAL_REVIEW_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_EXEMPT_NUMBER" ADD CONSTRAINT "MITKC_IRB_EXEMPT_NUMBER_FK2" FOREIGN KEY ("EXEMPTION_TYPE_CODE")
REFERENCES "EXEMPTION_TYPE" ("EXEMPTION_TYPE_CODE") ENABLE
/

--------------------------------------------------------
--  DDL for Table MITKC_IRB_CORRESPONDENCE
--------------------------------------------------------
CREATE TABLE "MITKC_IRB_CORRESPONDENCE" 
(	
"CORRESPONDENCE_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL, 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"ACTION_ID" NUMBER(6,0) NOT NULL, 
"PROTOCOL_ACTION_ID" NUMBER(12,0), 
"PROTO_CORRESP_TYPE_CODE" VARCHAR2(3 BYTE), 
"FINAL_FLAG" VARCHAR2(1 BYTE), 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL,
"CORRESPONDENCE" BLOB, 
"CREATE_TIMESTAMP" DATE NOT NULL, 
"CREATE_USER" VARCHAR2(60 BYTE) NOT NULL, 
"FINAL_FLAG_TIMESTAMP" DATE
)
/
CREATE UNIQUE INDEX "MITKC_IRB_CORRESPONDENCE_PK" ON "MITKC_IRB_CORRESPONDENCE" ("CORRESPONDENCE_ID") 
/
CREATE INDEX "MITKC_IRB_CORRESPONDENCE_IDX" ON "MITKC_IRB_CORRESPONDENCE" ("PROTOCOL_ACTION_ID") 
/
ALTER TABLE "MITKC_IRB_CORRESPONDENCE" ADD CONSTRAINT "MITKC_IRB_CORRESPONDENCE_PK" PRIMARY KEY ("CORRESPONDENCE_ID")
/
ALTER TABLE "MITKC_IRB_CORRESPONDENCE" ADD CONSTRAINT "MITKC_IRB_CORRESPONDENCE_FK1" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_CORRESPONDENCE" ADD CONSTRAINT "MITKC_IRB_CORRESPONDENCE_FK2" FOREIGN KEY ("PROTOCOL_ACTION_ID")
REFERENCES "MITKC_IRB_PROTOCOL_ACTIONS" ("PROTOCOL_ACTION_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_CORRESPONDENCE" ADD CONSTRAINT "MITKC_IRB_CORRESPONDENCE_FK3" FOREIGN KEY ("PROTO_CORRESP_TYPE_CODE")
REFERENCES "MITKC_IRB_PROTO_CORRESP_TYPE" ("PROTO_CORRESP_TYPE_CODE") ENABLE
/


--------------------------------------------------------
--  DDL for Table MITKC_IRB_RESEARCH_AREAS
--------------------------------------------------------
CREATE TABLE "MITKC_IRB_RESEARCH_AREAS" 
(	
"RESEARCH_AREA_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL, 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"RESEARCH_AREA_CODE" VARCHAR2(8 BYTE) NOT NULL, 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE)  NOT NULL

)
/
CREATE UNIQUE INDEX "MITKC_IRB_RESEARCH_AREAS_PK" ON "MITKC_IRB_RESEARCH_AREAS" ("RESEARCH_AREA_ID") 
/
ALTER TABLE "MITKC_IRB_RESEARCH_AREAS" ADD CONSTRAINT "MITKC_IRB_RESEARCH_AREAS_PK" PRIMARY KEY ("RESEARCH_AREA_ID")
/
ALTER TABLE "MITKC_IRB_RESEARCH_AREAS" ADD CONSTRAINT "MITKC_IRB_RESEARCH_AREAS_FK1" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_RESEARCH_AREAS" ADD CONSTRAINT "MITKC_IRB_RESEARCH_AREAS_FK2" FOREIGN KEY ("RESEARCH_AREA_CODE")
REFERENCES "RESEARCH_AREAS" ("RESEARCH_AREA_CODE") ENABLE
/
--------------------------------------------------------
--  DDL for Table MITKC_IRB_VOTE_ABSTAINEES
--------------------------------------------------------
CREATE TABLE "MITKC_IRB_VOTE_ABSTAINEES" 
(	
"PROTOCOL_VOTE_ABSTAINEES_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL, 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"PERSON_ID" VARCHAR2(40 BYTE), 
"NON_EMPLOYEE_FLAG" VARCHAR2(1 BYTE), 
"COMMENTS" VARCHAR2(2000 BYTE), 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL, 
"SUBMISSION_ID" NUMBER(12,0), 
"ROLODEX_ID" NUMBER(6,0), 
"IACUC_PROTOCOL_ID" NUMBER(12,0), 
"IACUC_SUBMISSION_ID" NUMBER(12,0)
)
/
CREATE UNIQUE INDEX "MITKC_IRB_VOTE_ABSTAINEES_PK" ON "MITKC_IRB_VOTE_ABSTAINEES" ("PROTOCOL_VOTE_ABSTAINEES_ID") 
/
ALTER TABLE "MITKC_IRB_VOTE_ABSTAINEES" ADD CONSTRAINT "MITKC_IRB_VOTE_ABSTAINEES_PK" PRIMARY KEY ("PROTOCOL_VOTE_ABSTAINEES_ID")
/
ALTER TABLE "MITKC_IRB_VOTE_ABSTAINEES" ADD CONSTRAINT "MITKC_IRB_VOTE_ABSTAINEES_FK1" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_VOTE_ABSTAINEES" ADD CONSTRAINT "MITKC_IRB_VOTE_ABSTAINEES_FK2" FOREIGN KEY ("ROLODEX_ID")
REFERENCES "ROLODEX" ("ROLODEX_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_VOTE_ABSTAINEES" ADD CONSTRAINT "MITKC_IRB_VOTE_ABSTAINEES_FK3" FOREIGN KEY ("SUBMISSION_ID")
REFERENCES "MITKC_IRB_PROTOCOL_SUBMISSION" ("SUBMISSION_ID") ENABLE
/


--------------------------------------------------------
--  DDL for Table MITKC_IRB_EXEMPT_CHKLST
--------------------------------------------------------
CREATE TABLE "MITKC_IRB_EXEMPT_CHKLST" 
(	
"PROTOCOL_EXEMPT_CHKLST_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL, 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"SUBMISSION_ID" NUMBER(12,0), 
"SUBMISSION_NUMBER" NUMBER(4,0), 
"EXEMPT_STUDIES_CHECKLIST_CODE" VARCHAR2(4 BYTE), 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL
)
/
CREATE UNIQUE INDEX "MITKC_IRB_EXEMPT_CHKLST_PK" ON "MITKC_IRB_EXEMPT_CHKLST" ("PROTOCOL_EXEMPT_CHKLST_ID") 
/
ALTER TABLE "MITKC_IRB_EXEMPT_CHKLST" ADD CONSTRAINT "MITKC_IRB_EXEMPT_CHKLST_PK" PRIMARY KEY ("PROTOCOL_EXEMPT_CHKLST_ID")
/
ALTER TABLE "MITKC_IRB_EXEMPT_CHKLST" ADD CONSTRAINT "MITKC_IRB_EXEMPT_CHKLST_FK1" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_EXEMPT_CHKLST" ADD CONSTRAINT "MITKC_IRB_EXEMPT_CHKLST_FK2" FOREIGN KEY ("SUBMISSION_ID")
REFERENCES "MITKC_IRB_PROTOCOL_SUBMISSION" ("SUBMISSION_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_EXEMPT_CHKLST" ADD CONSTRAINT "MITKC_IRB_EXEMPT_CHKLST_FK3" FOREIGN KEY ("EXEMPT_STUDIES_CHECKLIST_CODE")
REFERENCES "EXEMPT_STUDIES_CHECKLIST" ("EXEMPT_STUDIES_CHECKLIST_CODE") ENABLE
/

--------------------------------------------------------
--  DDL for Table MITKC_IRB_PROTO_SUBMISSION_DOC
--------------------------------------------------------
CREATE TABLE "MITKC_IRB_PROTO_SUBMISSION_DOC" 
(	
"SUBMISSION_DOC_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL, 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"SUBMISSION_NUMBER" NUMBER(4,0) NOT NULL, 
"SUBMISSION_ID" NUMBER(12,0) NOT NULL, 
"DOCUMENT_ID" NUMBER(3,0), 
"FILE_NAME" VARCHAR2(300 BYTE), 
"DOCUMENT" BLOB, 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL,
"DESCRIPTION" VARCHAR2(200 BYTE), 
"CONTENT_TYPE" VARCHAR2(255 BYTE)
)
/
CREATE UNIQUE INDEX "MITKC_IRB_SUBMISSION_DOC_PK" ON "MITKC_IRB_PROTO_SUBMISSION_DOC" ("SUBMISSION_DOC_ID") 
/
ALTER TABLE "MITKC_IRB_PROTO_SUBMISSION_DOC" ADD CONSTRAINT "MITKC_IRB_SUBMISSION_DOC_PK" PRIMARY KEY ("SUBMISSION_DOC_ID")
/
ALTER TABLE "MITKC_IRB_PROTO_SUBMISSION_DOC" ADD CONSTRAINT "MITKC_IRB_SUBMISSION_DOC_FK1" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTO_SUBMISSION_DOC" ADD CONSTRAINT "MITKC_IRB_SUBMISSION_DOC_FK2" FOREIGN KEY ("SUBMISSION_ID")
REFERENCES "MITKC_IRB_PROTOCOL_SUBMISSION" ("SUBMISSION_ID") ENABLE
/

--------------------------------------------------------
--  DDL for Table MITKC_IRB_PROTO_VULNERABLE_SUB
--------------------------------------------------------
CREATE TABLE "MITKC_IRB_PROTO_VULNERABLE_SUB" 
(	
"PROTOCOL_VULNERABLE_SUB_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL, 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"VULNERABLE_SUBJECT_TYPE_CODE" VARCHAR2(3 BYTE), 
"SUBJECT_COUNT" NUMBER(6,0), 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL
)
/
CREATE UNIQUE INDEX "MITKC_IRB_VULNERABLE_SUB_PK" ON "MITKC_IRB_PROTO_VULNERABLE_SUB" ("PROTOCOL_VULNERABLE_SUB_ID") 
/
CREATE INDEX "MITKC_IRB_VULNERABLE_SUB_UK1" ON "MITKC_IRB_PROTO_VULNERABLE_SUB" ("PROTOCOL_ID", "VULNERABLE_SUBJECT_TYPE_CODE") 
/
ALTER TABLE "MITKC_IRB_PROTO_VULNERABLE_SUB" ADD CONSTRAINT "MITKC_IRB_VULNERABLE_SUB_PK" PRIMARY KEY ("PROTOCOL_VULNERABLE_SUB_ID")
/
ALTER TABLE "MITKC_IRB_PROTO_VULNERABLE_SUB" ADD CONSTRAINT "MITKC_IRB_VULNERABLE_SUB_FK1" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_PROTO_VULNERABLE_SUB" ADD CONSTRAINT "MITKC_IRB_VULNERABLE_SUB_FK2" FOREIGN KEY ("VULNERABLE_SUBJECT_TYPE_CODE")
REFERENCES "VULNERABLE_SUBJECT_TYPE" ("VULNERABLE_SUBJECT_TYPE_CODE") ENABLE
/
CREATE TABLE "MITKC_IRB_EXPIDITED_CHKLST" 
(	
"PROTOCOL_EXPEDITED_CHKLST_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL, 
"SUBMISSION_ID" NUMBER(12,0), 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"SUBMISSION_NUMBER" NUMBER(4,0) NOT NULL, 
"EXPEDITED_REV_CHKLST_CODE" VARCHAR2(4 BYTE), 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL
)
/
CREATE UNIQUE INDEX "MITKC_IRB_EXPIDITED_CHKLST_PK" ON "MITKC_IRB_EXPIDITED_CHKLST" ("PROTOCOL_EXPEDITED_CHKLST_ID") 
/
ALTER TABLE "MITKC_IRB_EXPIDITED_CHKLST" ADD CONSTRAINT "MITKC_IRB_EXPIDITED_CHKLST_PK" PRIMARY KEY ("PROTOCOL_EXPEDITED_CHKLST_ID")
/
ALTER TABLE "MITKC_IRB_EXPIDITED_CHKLST" ADD CONSTRAINT "MITKC_IRB_EXPIDITED_CHKLST_FK1" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_EXPIDITED_CHKLST" ADD CONSTRAINT "MITKC_IRB_EXPIDITED_CHKLST_FK2" FOREIGN KEY ("SUBMISSION_ID")
REFERENCES "MITKC_IRB_PROTOCOL_SUBMISSION" ("SUBMISSION_ID") ENABLE
/
ALTER TABLE "MITKC_IRB_EXPIDITED_CHKLST" ADD CONSTRAINT "MITKC_IRB_EXPIDITED_CHKLST_FK3" FOREIGN KEY ("EXPEDITED_REV_CHKLST_CODE")
REFERENCES "EXPEDITED_REVIEW_CHECKLIST" ("EXPEDITED_REV_CHKLST_CODE") ENABLE
/
CREATE TABLE "MITKC_IRB_PROTOCOL_NOTEPAD" 
(	"PROTOCOL_NOTEPAD_ID" NUMBER(12,0), 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL, 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
"SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL, 
"ENTRY_NUMBER" NUMBER(4,0), 
"COMMENTS" CLOB, 
"RESTRICTED_VIEW" VARCHAR2(1 BYTE), 
"NOTE_TYPE" VARCHAR2(60 BYTE), 
"UPDATE_TIMESTAMP" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL, 
"CREATE_TIMESTAMP" DATE NOT NULL, 
"CREATE_USER" VARCHAR2(60 BYTE) NOT NULL
)
/
CREATE UNIQUE INDEX "MITKC_IRB_PROTOCOL_NOTEPAD_PK" ON "MITKC_IRB_PROTOCOL_NOTEPAD" ("PROTOCOL_NOTEPAD_ID") 
/
CREATE INDEX "MITKC_IRB_PROTOCOL_NOTEPAD_UK" ON "MITKC_IRB_PROTOCOL_NOTEPAD" ("PROTOCOL_NUMBER", "ENTRY_NUMBER") 
/
ALTER TABLE "MITKC_IRB_PROTOCOL_NOTEPAD" ADD CONSTRAINT "MITKC_IRB_PROTOCOL_NOTEPAD_PK" PRIMARY KEY ("PROTOCOL_NOTEPAD_ID")
/
ALTER TABLE "MITKC_IRB_PROTOCOL_NOTEPAD" ADD CONSTRAINT "MITKC_IRB_PROTOCOL_NOTEPAD_FK1" FOREIGN KEY ("PROTOCOL_ID")
REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
/
CREATE TABLE "MITKC_IRB_AMEND_RENEWAL" 
(	"PROTO_AMEND_RENEWAL_ID" NUMBER(12,0), 
"PROTO_AMEND_REN_NUMBER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
"DATE_CREATED" DATE NOT NULL ENABLE, 
"SUMMARY" CLOB, 
"PROTOCOL_ID" NUMBER(12,0) NOT NULL ENABLE, 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE), 
"SEQUENCE_NUMBER" NUMBER(4,0), 
"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
CONSTRAINT "MITKC_IRB_AMEND_RENEWAL_PK" PRIMARY KEY ("PROTO_AMEND_RENEWAL_ID"), 
CONSTRAINT "MITKC_IRB_AMEND_RENEWAL_FK1" FOREIGN KEY ("PROTOCOL_ID") REFERENCES "MITKC_IRB_PROTOCOL" ("PROTOCOL_ID") ENABLE
) 
/
CREATE INDEX "MITKC_IRB_AMEND_RENEWAL_IDX1" ON "MITKC_IRB_AMEND_RENEWAL" ("PROTOCOL_ID") 
/
CREATE TABLE "MITKC_IRB_AMEND_RENEW_MODULES" 
(	"PROTO_AMEND_RENEW_MODULES_ID" NUMBER(12,0), 
"PROTO_AMEND_RENEWAL_NUMBER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
"PROTO_AMEND_RENEWAL_ID" NUMBER(12,0) NOT NULL ENABLE, 
"PROTOCOL_NUMBER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
"PROTOCOL_MODULE_CODE" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
CONSTRAINT "MITKC_IRB_AMEND_RENEW_MOD_PK" PRIMARY KEY ("PROTO_AMEND_RENEW_MODULES_ID"), 
CONSTRAINT "MITKC_IRB_AMEND_RENEW_MOD_FK1" FOREIGN KEY ("PROTO_AMEND_RENEWAL_ID") REFERENCES "MITKC_IRB_AMEND_RENEWAL" ("PROTO_AMEND_RENEWAL_ID") ENABLE, 
CONSTRAINT "MITKC_IRB_AMEND_RENEW_MOD_FK2" FOREIGN KEY ("PROTOCOL_MODULE_CODE") REFERENCES "MITKC_IRB_PROTOCOL_MODULES" ("PROTOCOL_MODULE_CODE") ENABLE
)
/