CREATE TABLE MITKC_IRB_EXEMPT_ACTION_TYPE(
"ACTION_TYPE_CODE" VARCHAR2(3 BYTE), 
"DESCRIPTION" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
"UPDATE_USER" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
CONSTRAINT "MITKC_IRB_EXEMPT_ACTION_TYP_PK" PRIMARY KEY ("ACTION_TYPE_CODE")
)
/
INSERT INTO "MITKC_IRB_EXEMPT_ACTION_TYPE" (ACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('1', 'Created', sysdate, user)
/
INSERT INTO "MITKC_IRB_EXEMPT_ACTION_TYPE" (ACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('2', 'Submitted', sysdate, user)
/
INSERT INTO "MITKC_IRB_EXEMPT_ACTION_TYPE" (ACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('3', 'Approved by Faculty sponsor', sysdate, user)
/
INSERT INTO "MITKC_IRB_EXEMPT_ACTION_TYPE" (ACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('4', 'Returned by Faculty sponsor', sysdate, user)
/
INSERT INTO "MITKC_IRB_EXEMPT_ACTION_TYPE" (ACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('5', 'Returned by IRB Office', sysdate, user)
/
INSERT INTO "MITKC_IRB_EXEMPT_ACTION_TYPE" (ACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('6', 'Approved by IRB Office', sysdate, user)
/
INSERT INTO "MITKC_IRB_EXEMPT_ACTION_TYPE" (ACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('7', 'Returned by PI', sysdate, user)
/
INSERT INTO "MITKC_IRB_EXEMPT_ACTION_TYPE" (ACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('8', 'Approved by PI', sysdate, user)
/
INSERT INTO "MITKC_IRB_EXEMPT_FORM_STATUS" (EXEMPT_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('3', 'Enroute to IRB office', sysdate, user)
/
INSERT INTO "MITKC_IRB_EXEMPT_FORM_STATUS" (EXEMPT_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('4', 'Submitted', sysdate, user)
/
INSERT INTO "MITKC_IRB_EXEMPT_FORM_STATUS" (EXEMPT_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('5', 'Enroute to PI', sysdate, user)
/
UPDATE MITKC_IRB_EXEMPT_FORM_STATUS
SET DESCRIPTION = 'Enroute to Faculty sponsor'
WHERE EXEMPT_STATUS_CODE = 2
/
UPDATE MITKC_IRB_PERSON_EXEMPT_FORM
SET EXEMPT_STATUS_CODE = 4
WHERE EXEMPT_STATUS_CODE = 2
/
CREATE TABLE "MITKC_IRB_EXEMPT_FORM_ACTN_LOG" 
(	
"EXEMPT_FORM_ACTN_LOG_ID"		NUMBER(12,0), 
"IRB_PERSON_EXEMPT_FORM_ID"		NUMBER(12,0), 
"ACTION_TYPE_CODE" 				VARCHAR2(3 BYTE),
"COMMENTS"						VARCHAR2(4000),
"EXEMPT_STATUS_CODE" 			VARCHAR2(3 BYTE),
"UPDATE_TIMESTAMP" 				DATE NOT NULL, 
"UPDATE_USER" 					VARCHAR2(60 BYTE) NOT NULL
)
/
CREATE UNIQUE INDEX "MITKC_IRB_EXEMPT_ACTN_LOG_IDX" ON "MITKC_IRB_EXEMPT_FORM_ACTN_LOG" ("EXEMPT_FORM_ACTN_LOG_ID") 
/
ALTER TABLE "MITKC_IRB_EXEMPT_FORM_ACTN_LOG" ADD CONSTRAINT "MITKC_IRB_EXEMPT_ACTN_LOG_PK" PRIMARY KEY ("EXEMPT_FORM_ACTN_LOG_ID")
/
ALTER TABLE "MITKC_IRB_EXEMPT_FORM_ACTN_LOG" ADD CONSTRAINT "MITKC_IRB_EXEMPT_ACTN_LOG_FK1" FOREIGN KEY ("ACTION_TYPE_CODE")
REFERENCES "MITKC_IRB_EXEMPT_ACTION_TYPE" ("ACTION_TYPE_CODE") ENABLE
/
CREATE SEQUENCE  "SEQ_EXEMPT_FORM_ACTN_LOG_ID"  
MINVALUE 1 
MAXVALUE 999999999999 
INCREMENT BY 1
START WITH 1
NOCACHE 
NOORDER 
NOCYCLE
/
CREATE TABLE MITKC_IRB_EXEMPT_FORM_CHECKLST(
EXEMPT_FORM_CHECKLST_ID			NUMBER(12,0), 
IRB_PERSON_EXEMPT_FORM_ID		NUMBER(12,0), 
DESCRIPTION VARCHAR2(200 BYTE) NOT NULL ENABLE, 
FILENAME	VARCHAR2(500 BYTE),
FILE_DATA	BLOB,
CONTENT_TYPE	VARCHAR2(255 BYTE),
UPDATE_TIMESTAMP	DATE,
UPDATE_USER	VARCHAR2(8 BYTE), 
CONSTRAINT "MITKC_IRB_EXEMPT_FRM_CHKLST_PK" PRIMARY KEY ("EXEMPT_FORM_CHECKLST_ID")
)
/
CREATE SEQUENCE  "SEQ_EXEMPT_FORM_CHECKLST_ID"  
MINVALUE 1 
MAXVALUE 999999999999 
INCREMENT BY 1
START WITH 1
NOCACHE 
NOORDER 
NOCYCLE
/
ALTER TABLE "MITKC_IRB_PERSON_EXEMPT_FORM" ADD START_DATE  DATE
/
ALTER TABLE "MITKC_IRB_PERSON_EXEMPT_FORM" ADD END_DATE  DATE
/
