package org.mit.irb.web.common.constants;

/**
 * Constants in MIT IRB
 *
 */
public final class KeyConstants {

	public static final String REQUESTED_URL = "REQUESTED_URL";
	
	public static final Integer COEUS_MODULE_PERSON = 6;
	
	public static final String AWARD_SEQUENCE_STATUS_ACTIVE = "ACTIVE";
	
	public static final String SPONSOR_FUNDING_SPONSOR_TYPE_CODE = "1";	
	public static final String UNIT_FUNDING_SPONSOR_TYPE_CODE = "2";	
	public static final String DEV_PROP_FUNDING_SPONSOR_TYPE_CODE = "4";	
	public static final String PROPOSAL_FUNDING_SPONSOR_TYPE_CODE = "5";
	public static final String AWARD_FUNDING_SPONSOR_TYPE_CODE = "6";
	
	public static final Integer PROTOCOL_MINUTE_ENTRY_TYPE = 3;
	/*Action Code*/
	public static final String CREATE_AMENDMENT_ACTION_CODE = "103";
	public static final String NOTIFY_COHEUS_ACTION_CODE = "116";
	
	/*Module Code*/
	public static final Integer PROTOCOL_MODULE_CODE = 7;
	
	public static final String ROLE_WITH_UNIT = "SELECT DISTINCT T1.PERSON_ID,T2.FULL_NAME,T2.EMAIL_ADDRESS,T2.USER_NAME,T3.UNIT_NAME,T1.UNIT_NUMBER\r\n" + 
			"FROM IRB_PERSON_ROLES_ASSIGN T1 \r\n" + 
			"INNER JOIN WHOSP_PERSON_HISTORY T2 ON T1.PERSON_ID = T2.PERSON_ID\r\n" + 
			"INNER JOIN UNIT T3 ON T1.UNIT_NUMBER = T3.UNIT_NUMBER WHERE T1.UNIT_NUMBER = :unit_number";

	public static final String ROLE_WITH_ROLE = "SELECT DISTINCT T1.PERSON_ID,T2.FULL_NAME,T2.EMAIL_ADDRESS,T2.USER_NAME,T3.UNIT_NAME,T1.UNIT_NUMBER\r\n" + 
			"FROM IRB_PERSON_ROLES_ASSIGN T1 \r\n" + 
			"INNER JOIN WHOSP_PERSON_HISTORY T2 ON T1.PERSON_ID = T2.PERSON_ID\r\n" + 
			"INNER JOIN UNIT T3 ON T1.UNIT_NUMBER = T3.UNIT_NUMBER WHERE T1.ROLE_ID = :role_id";

	public static final String ROLE_WITH_UNIT_AND_ROLE = "SELECT DISTINCT T1.PERSON_ID,T2.FULL_NAME,T2.EMAIL_ADDRESS,T2.USER_NAME,T3.UNIT_NAME,T1.UNIT_NUMBER\r\n" + 
			"FROM IRB_PERSON_ROLES_ASSIGN T1 \r\n" + 
			"INNER JOIN WHOSP_PERSON_HISTORY T2 ON T1.PERSON_ID = T2.PERSON_ID\r\n" + 
			"INNER JOIN UNIT T3 ON T1.UNIT_NUMBER = T3.UNIT_NUMBER WHERE T1.ROLE_ID = :role_id AND T1.UNIT_NUMBER = :unit_number";

	public static final String FETCH_ALL_ROLES= "SELECT DISTINCT T1.PERSON_ID,T2.FULL_NAME,T2.EMAIL_ADDRESS,T2.USER_NAME,T3.UNIT_NAME,T1.UNIT_NUMBER\r\n" + 
			"FROM IRB_PERSON_ROLES_ASSIGN T1 \r\n" + 
			"INNER JOIN WHOSP_PERSON_HISTORY T2 ON T1.PERSON_ID = T2.PERSON_ID\r\n" + 
			"INNER JOIN UNIT T3 ON T1.UNIT_NUMBER = T3.UNIT_NUMBER";
	
	public static final String ROLES_OF_PERSON = "SELECT DISTINCT T1.PERSON_ID,T2.FULL_NAME,T2.EMAIL_ADDRESS,T2.USER_NAME,T3.UNIT_NAME,T1.UNIT_NUMBER\r\n" + 
			"			FROM IRB_PERSON_ROLES_ASSIGN T1\r\n" + 
			"			INNER JOIN WHOSP_PERSON_HISTORY T2 ON T1.PERSON_ID = T2.PERSON_ID \r\n" + 
			"			INNER JOIN UNIT T3 ON T1.UNIT_NUMBER = T3.UNIT_NUMBER WHERE T1.PERSON_ID = :person_id\r\n" ; 
			//"			GROUP BY T1.UNIT_NUMBER ";
}
