ALTER TABLE MITKC_ELASTIC_INDEX ADD SUBMISSION_STATUS VARCHAR2(200)
/
ALTER TABLE MITKC_ELASTIC_INDEX ADD APPROVAL_DATE VARCHAR2(10)
/
ALTER TABLE MITKC_ELASTIC_INDEX ADD EXPIRATION_DATE VARCHAR2(10)
/
ALTER TABLE MITKC_ELASTIC_INDEX MODIFY MODULE_ITEM_KEY VARCHAR2(20)
/
ALTER TABLE MITKC_ELASTIC_INDEX MODIFY TITLE VARCHAR2(1000)
/
